from pathlib import Path
p=Path(__file__).resolve().parents[1]/'app'/'src'/'main'/'assets'/'index.html'
s=p.read_text(encoding='utf-8')
if 'living-dex-personal-music" content="7.12.0"' not in s:
    s=s.replace('</head>','<meta name="living-dex-personal-music" content="7.12.0"/>\n</head>',1)
css=r'''
/* Personal Music Library 7.12 — user-imported local audio only */
#ldh712MusicQuick{position:fixed;right:14px;top:calc(14px + env(safe-area-inset-top));z-index:7600;width:42px;height:42px;border:1px solid rgba(18,46,73,.12);border-radius:14px;background:rgba(255,255,255,.94);backdrop-filter:blur(16px);box-shadow:0 8px 24px rgba(15,34,56,.12);display:grid;place-items:center;font-size:18px;color:#17324d;cursor:pointer}
#ldh712MusicQuick.playing{box-shadow:0 8px 24px rgba(15,34,56,.12),0 0 0 3px rgba(58,143,255,.10)}
#ldh712MusicModal{position:fixed;inset:0;z-index:9000;display:none;align-items:flex-end;justify-content:center;background:rgba(10,22,36,.42);backdrop-filter:blur(7px)}
#ldh712MusicModal.open{display:flex}
.ldh712-sheet{width:min(680px,100%);max-height:min(78vh,720px);overflow:auto;background:#f7f8fb;border-radius:26px 26px 0 0;padding:18px 16px calc(20px + env(safe-area-inset-bottom));box-shadow:0 -20px 60px rgba(5,20,38,.18)}
.ldh712-head{display:flex;align-items:flex-start;justify-content:space-between;gap:14px;margin-bottom:14px}.ldh712-head h3{margin:2px 0 4px;font-size:19px;color:#172b40}.ldh712-head p{margin:0;font-size:11px;line-height:1.45;color:#718296}.ldh712-close{width:36px;height:36px;border:0;border-radius:12px;background:#e9edf3;color:#243b53;font-size:17px}
.ldh712-now{padding:14px;border-radius:18px;background:#fff;border:1px solid #e5eaf0;box-shadow:0 6px 18px rgba(20,38,58,.05);margin-bottom:12px}.ldh712-eyebrow{font-size:9px;text-transform:uppercase;letter-spacing:.12em;font-weight:800;color:#6b7e91}.ldh712-title{font-size:14px;font-weight:800;color:#1b3045;margin-top:4px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.ldh712-controls{display:grid;grid-template-columns:auto 1fr auto;gap:10px;align-items:center;margin-top:12px}.ldh712-play{width:42px;height:42px;border:0;border-radius:14px;background:#17324d;color:#fff;font-size:17px}.ldh712-controls input[type=range]{width:100%;accent-color:#17324d}.ldh712-vol{font-size:10px;color:#718296;min-width:34px;text-align:right}.ldh712-import{width:100%;border:0;border-radius:15px;padding:13px 14px;background:#17324d;color:#fff;font-size:12px;font-weight:800;margin:4px 0 12px}.ldh712-list{display:grid;gap:8px}.ldh712-track{display:grid;grid-template-columns:1fr auto;gap:10px;align-items:center;background:#fff;border:1px solid #e5eaf0;border-radius:15px;padding:11px 12px}.ldh712-track.active{border-color:#a8c7ed;background:#f9fcff}.ldh712-track-main{min-width:0;cursor:pointer}.ldh712-track b{display:block;font-size:12px;color:#20364c;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.ldh712-track small{display:block;margin-top:2px;font-size:9px;color:#8392a3}.ldh712-remove{width:32px;height:32px;border:0;border-radius:10px;background:#f0f2f5;color:#7d8794;font-size:15px}.ldh712-empty{padding:18px;text-align:center;border:1px dashed #ccd6e1;border-radius:16px;color:#7a8b9d;font-size:11px;line-height:1.5}.ldh712-note{font-size:9px;line-height:1.5;color:#8a98a8;margin-top:12px}
@media(max-width:520px){#ldh712MusicQuick{right:10px;top:calc(10px + env(safe-area-inset-top));width:40px;height:40px}.ldh712-sheet{max-height:82vh}}
'''
if '/* Personal Music Library 7.12' not in s:s=s.replace('</style>',css+'\n</style>',1)
js=r'''
// Personal Music Library 7.12 — imports audio from the user's device into IndexedDB.
const LD712_DB='ldh_personal_music_v712',LD712_STORE='tracks',LD712_PREF='ldh_personal_music_prefs_v712';
let ld712Db=null,ld712ObjectUrl=null,ld712Tracks=[];
let ld712Prefs=(()=>{try{return Object.assign({selected:null,volume:.35,shouldPlay:false},JSON.parse(localStorage.getItem(LD712_PREF)||'{}'))}catch(e){return {selected:null,volume:.35,shouldPlay:false}}})();
function ld712Persist(){try{localStorage.setItem(LD712_PREF,JSON.stringify(ld712Prefs))}catch(e){}}
function ld712OpenDb(){return new Promise((resolve,reject)=>{if(ld712Db)return resolve(ld712Db);const r=indexedDB.open(LD712_DB,1);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(LD712_STORE))d.createObjectStore(LD712_STORE,{keyPath:'id'})};r.onsuccess=()=>{ld712Db=r.result;resolve(ld712Db)};r.onerror=()=>reject(r.error)})}
async function ld712GetAll(){const d=await ld712OpenDb();return new Promise((resolve,reject)=>{const r=d.transaction(LD712_STORE,'readonly').objectStore(LD712_STORE).getAll();r.onsuccess=()=>resolve(r.result||[]);r.onerror=()=>reject(r.error)})}
async function ld712Put(track){const d=await ld712OpenDb();return new Promise((resolve,reject)=>{const r=d.transaction(LD712_STORE,'readwrite').objectStore(LD712_STORE).put(track);r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error)})}
async function ld712Delete(id){const d=await ld712OpenDb();return new Promise((resolve,reject)=>{const r=d.transaction(LD712_STORE,'readwrite').objectStore(LD712_STORE).delete(id);r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error)})}
function ld712Audio(){let a=document.getElementById('ldh712Audio');if(!a){a=document.createElement('audio');a.id='ldh712Audio';a.loop=true;a.preload='auto';a.style.display='none';a.volume=ld712Prefs.volume;a.addEventListener('play',()=>{ld712Prefs.shouldPlay=true;ld712Persist();ld712Render()});a.addEventListener('pause',()=>{ld712Render()});document.body.appendChild(a)}return a}
function ld712DisplayName(name='Música'){let n=name.replace(/\.(mp3|m4a|ogg|opus|wav|aac|flac)$/i,'').replace(/[_]+/g,' ').replace(/\s+/g,' ').trim();if(/littleroot\s+town/i.test(n))return 'Littleroot Town';return n||'Música'}
function ld712Size(bytes){if(!bytes)return '';const mb=bytes/1048576;return mb>=1?mb.toFixed(mb>=10?0:1)+' MB':Math.round(bytes/1024)+' KB'}
async function ld712Refresh(){try{ld712Tracks=(await ld712GetAll()).sort((a,b)=>(a.addedAt||0)-(b.addedAt||0));if(ld712Prefs.selected&&!ld712Tracks.some(t=>t.id===ld712Prefs.selected)){ld712Prefs.selected=ld712Tracks[0]?.id||null;ld712Prefs.shouldPlay=false;ld712Persist()}ld712Render();if(ld712Prefs.selected)await ld712LoadSelected(false)}catch(e){console.warn('Living Dex Hub: personal music database unavailable',e)}}
async function ld712LoadSelected(play=false){const t=ld712Tracks.find(x=>x.id===ld712Prefs.selected),a=ld712Audio();if(!t){a.pause();a.removeAttribute('src');return}if(ld712ObjectUrl)URL.revokeObjectURL(ld712ObjectUrl);ld712ObjectUrl=URL.createObjectURL(t.blob);a.src=ld712ObjectUrl;a.volume=ld712Prefs.volume;if(play||ld712Prefs.shouldPlay){try{await a.play()}catch(e){}}ld712Render()}
async function ld712Select(id){ld712Prefs.selected=id;ld712Prefs.shouldPlay=true;ld712Persist();await ld712LoadSelected(true)}
function ld712Toggle(){const a=ld712Audio();if(!ld712Prefs.selected){ld712Open();return}if(a.paused){ld712Prefs.shouldPlay=true;ld712Persist();a.play().catch(()=>{})}else{ld712Prefs.shouldPlay=false;ld712Persist();a.pause()}ld712Render()}
function ld712Volume(v){ld712Prefs.volume=Math.max(0,Math.min(1,Number(v)));ld712Persist();ld712Audio().volume=ld712Prefs.volume;ld712Render()}
function ld712Pick(){document.getElementById('ldh712File')?.click()}
async function ld712Import(input){const files=Array.from(input.files||[]);input.value='';if(!files.length)return;for(const f of files){if(!String(f.type||'').startsWith('audio/')&&!/\.(mp3|m4a|ogg|opus|wav|aac|flac)$/i.test(f.name||''))continue;const id='t_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,8);await ld712Put({id,name:ld712DisplayName(f.name),fileName:f.name,type:f.type||'audio/mpeg',size:f.size||0,blob:f,addedAt:Date.now()});if(!ld712Prefs.selected)ld712Prefs.selected=id}ld712Prefs.shouldPlay=true;ld712Persist();await ld712Refresh();if(ld712Prefs.selected)await ld712LoadSelected(true)}
async function ld712Remove(id){const t=ld712Tracks.find(x=>x.id===id);if(!t)return;if(!confirm('Remover “'+t.name+'” da biblioteca de músicas deste aparelho?'))return;await ld712Delete(id);if(ld712Prefs.selected===id){ld712Prefs.selected=null;ld712Prefs.shouldPlay=false;ld712Audio().pause()}ld712Persist();await ld712Refresh()}
function ld712Open(){const m=document.getElementById('ldh712MusicModal');if(m){m.classList.add('open');m.setAttribute('aria-hidden','false');ld712Render()}}
function ld712Close(){const m=document.getElementById('ldh712MusicModal');if(m){m.classList.remove('open');m.setAttribute('aria-hidden','true')}}
function ld712Render(){const a=document.getElementById('ldh712Audio'),playing=!!a&&!a.paused&&!!a.src,sel=ld712Tracks.find(t=>t.id===ld712Prefs.selected);const q=document.getElementById('ldh712MusicQuick');if(q){q.classList.toggle('playing',playing);q.textContent=playing?'♫':'♪';q.title=playing?'Música tocando':'Música'}const title=document.getElementById('ldh712NowTitle');if(title)title.textContent=sel?sel.name:'Nenhuma música selecionada';const p=document.getElementById('ldh712Play');if(p){p.textContent=playing?'Ⅱ':'▶';p.setAttribute('aria-label',playing?'Pausar':'Reproduzir')}const vr=document.getElementById('ldh712VolumeLabel');if(vr)vr.textContent=Math.round(ld712Prefs.volume*100)+'%';const range=document.getElementById('ldh712Volume');if(range&&document.activeElement!==range)range.value=ld712Prefs.volume;const list=document.getElementById('ldh712TrackList');if(list){list.innerHTML=ld712Tracks.length?ld712Tracks.map(t=>`<div class="ldh712-track ${t.id===ld712Prefs.selected?'active':''}"><div class="ldh712-track-main" onclick="ld712Select('${t.id}')"><b>${ld712Esc(t.name)}</b><small>${ld712Esc(t.fileName||'Arquivo local')}${t.size?' · '+ld712Size(t.size):''}</small></div><button class="ldh712-remove" type="button" aria-label="Remover música" onclick="ld712Remove('${t.id}')">×</button></div>`).join(''):'<div class="ldh712-empty">Sua biblioteca está vazia.<br>Importe um arquivo de áudio que já esteja no seu celular.</div>'}}
function ld712Esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function ld712Mount(){
 // Disable only the old generated background melody. Existing lightweight UI SFX remain available.
 try{if(ldhLoopTimer){clearInterval(ldhLoopTimer);ldhLoopTimer=null}ldhScheduleStep=function(){}}catch(e){}
 if(!document.getElementById('ldh712Audio'))ld712Audio();
 if(!document.getElementById('ldh712MusicQuick')){const q=document.createElement('button');q.id='ldh712MusicQuick';q.type='button';q.textContent='♪';q.setAttribute('aria-label','Músicas');q.onclick=ld712Open;document.body.appendChild(q)}
 if(!document.getElementById('ldh712MusicModal')){const m=document.createElement('div');m.id='ldh712MusicModal';m.setAttribute('aria-hidden','true');m.innerHTML=`<div class="ldh712-sheet" role="dialog" aria-modal="true" aria-label="Biblioteca de músicas"><div class="ldh712-head"><div><h3>Músicas</h3><p>Trilhas pessoais armazenadas somente neste aparelho.</p></div><button class="ldh712-close" type="button" onclick="ld712Close()" aria-label="Fechar">×</button></div><div class="ldh712-now"><div class="ldh712-eyebrow">Tocando agora</div><div class="ldh712-title" id="ldh712NowTitle">Nenhuma música selecionada</div><div class="ldh712-controls"><button class="ldh712-play" id="ldh712Play" type="button" onclick="ld712Toggle()">▶</button><input id="ldh712Volume" type="range" min="0" max="1" step="0.02" value="${ld712Prefs.volume}" oninput="ld712Volume(this.value)"><span class="ldh712-vol" id="ldh712VolumeLabel">${Math.round(ld712Prefs.volume*100)}%</span></div></div><input id="ldh712File" type="file" accept="audio/mpeg,audio/mp4,audio/ogg,audio/wav,audio/*" multiple hidden onchange="ld712Import(this)"><button class="ldh712-import" type="button" onclick="ld712Pick()">+ Importar música do celular</button><div class="ldh712-list" id="ldh712TrackList"></div><div class="ldh712-note">Os arquivos importados ficam salvos localmente no armazenamento do aplicativo e não são enviados para o repositório.</div></div>`;m.addEventListener('click',e=>{if(e.target===m)ld712Close()});document.body.appendChild(m)}
 ld712Refresh();ld712Render();
}
const ld712OldBack=window.androidHandleBack;window.androidHandleBack=function(){const m=document.getElementById('ldh712MusicModal');if(m?.classList.contains('open')){ld712Close();return true}return typeof ld712OldBack==='function'?ld712OldBack.apply(this,arguments):false};
document.addEventListener('visibilitychange',()=>{const a=document.getElementById('ldh712Audio');if(!a)return;if(document.hidden){if(!a.paused){ld712Prefs.shouldPlay=true;ld712Persist();a.pause()}}else if(ld712Prefs.shouldPlay&&ld712Prefs.selected){a.play().catch(()=>{})}});
window.ld712Audit=function(){const a=document.getElementById('ldh712Audio');return {version:'7.12.0',tracks:ld712Tracks.length,selected:ld712Prefs.selected,playing:!!a&&!a.paused,volume:ld712Prefs.volume,indexedDb:!!window.indexedDB,quick:!!document.getElementById('ldh712MusicQuick'),modal:!!document.getElementById('ldh712MusicModal')}};
setTimeout(ld712Mount,0);
'''
s=s.replace('</body>','<script>'+js+'</script>\n</body>',1)
p.write_text(s,encoding='utf-8')
print('Personal Music Library 7.12 applied')
