from pathlib import Path
p=Path(__file__).resolve().parents[1]/'app'/'src'/'main'/'assets'/'index.html'
s=p.read_text(encoding='utf-8')
if 'living-dex-journey-plus" content="1.8"' not in s:s=s.replace('</head>','<meta name="living-dex-journey-plus" content="1.8"/>\n</head>',1)
css=r'''
/* Journey 1.8 — boss prep, researched story builds, richer Paldea route */
.next-objective{display:grid;grid-template-columns:1fr auto;gap:14px;align-items:center;padding:18px;border-radius:22px;border:1px solid rgba(114,213,255,.18);background:radial-gradient(320px 160px at 95% 0,rgba(79,181,255,.14),transparent 65%),rgba(255,255,255,.025);margin-bottom:12px}.next-objective .kicker{font-size:9px;letter-spacing:.14em;text-transform:uppercase;color:#72d5ff;font-weight:900}.next-objective h3{margin:5px 0;font-size:19px}.next-objective p{margin:0;color:#93a8c0;font-size:10px;line-height:1.5}.next-level{width:62px;height:62px;border-radius:20px;display:grid;place-items:center;background:rgba(102,224,173,.08);border:1px solid rgba(102,224,173,.18);font-weight:900;text-align:center}.next-level small{display:block;font-size:7px;color:#92aa9f}.prep-row{display:flex;gap:6px;flex-wrap:wrap;margin-top:9px}.prep-chip{font-size:8px;font-weight:800;border-radius:999px;padding:6px 8px;border:1px solid rgba(148,180,215,.13);background:rgba(255,255,255,.025);color:#bed0e0}.journey-progressline{height:7px;background:rgba(255,255,255,.055);border-radius:999px;overflow:hidden;margin:11px 0 0}.journey-progressline i{display:block;height:100%;background:linear-gradient(90deg,#4fb5ff,#66e0ad)}
.team-poke{cursor:pointer;position:relative}.team-poke .owned-dot{position:absolute;right:9px;top:9px;width:9px;height:9px;border-radius:50%;background:#506277;border:2px solid #112034}.team-poke .owned-dot.yes{background:#66e0ad;box-shadow:0 0 14px rgba(102,224,173,.65)}.build-sheet{position:fixed;inset:0;z-index:9000;background:rgba(3,9,17,.76);backdrop-filter:blur(16px);display:flex;align-items:flex-end;justify-content:center}.build-card{width:min(720px,100%);max-height:90vh;overflow:auto;border-radius:28px 28px 0 0;border:1px solid rgba(148,180,215,.15);background:linear-gradient(180deg,#10243a,#091726);padding:20px 18px calc(22px + env(safe-area-inset-bottom));box-shadow:0 -30px 80px rgba(0,0,0,.45)}.build-head{display:grid;grid-template-columns:88px 1fr auto;gap:14px;align-items:center}.build-head img{width:88px;height:88px;object-fit:contain}.build-head h3{margin:0 0 4px;font-size:23px}.build-head p{margin:0;color:#91a7bd;font-size:10px}.build-meta{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:16px 0}.build-meta div,.move{padding:11px;border-radius:14px;background:rgba(255,255,255,.028);border:1px solid rgba(148,180,215,.11)}.build-meta small,.move small{display:block;color:#8096ac;font-size:7px;text-transform:uppercase;letter-spacing:.09em;margin-bottom:4px}.build-meta b{font-size:10px}.moves-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.move b{font-size:10px}.build-note{margin-top:12px;padding:12px;border-radius:15px;background:rgba(79,181,255,.06);border:1px solid rgba(79,181,255,.12);font-size:9px;line-height:1.55;color:#a9bed2}.research-note{font-size:8px;color:#748ba2;line-height:1.5;margin-top:11px}.research-note a{color:#83d8ff;text-decoration:none}
.paldea-map{position:relative;min-height:620px;border-radius:26px;overflow:hidden;border:1px solid rgba(148,180,215,.13);background:radial-gradient(circle at 51% 42%,rgba(44,128,105,.30),transparent 30%),radial-gradient(circle at 52% 40%,#153b38 0 35%,#0c2730 36% 51%,#071a2a 52%);box-shadow:inset 0 0 80px rgba(0,0,0,.25)}.paldea-land{position:absolute;left:13%;top:9%;width:74%;height:80%;background:linear-gradient(145deg,rgba(83,143,93,.34),rgba(159,132,70,.20));clip-path:polygon(45% 0,63% 7%,78% 18%,88% 35%,83% 53%,94% 67%,75% 81%,60% 96%,42% 89%,27% 98%,15% 80%,4% 62%,12% 45%,3% 27%,20% 12%);border-radius:45%;filter:drop-shadow(0 20px 30px rgba(0,0,0,.25))}.paldea-center{position:absolute;left:43%;top:36%;width:15%;aspect-ratio:1;border-radius:50%;border:2px dashed rgba(255,255,255,.13);background:rgba(8,18,27,.38)}.geo-node{position:absolute;z-index:3;width:34px;height:34px;border-radius:50%;border:2px solid rgba(255,255,255,.28);background:#102b43;color:#fff;font-size:9px;font-weight:900;display:grid;place-items:center;box-shadow:0 7px 20px rgba(0,0,0,.38);transform:translate(-50%,-50%)}.geo-node.gym{background:#1d4b72}.geo-node.titan{background:#745328}.geo-node.star{background:#6a3146}.geo-node.done{opacity:.42}.geo-node.next{width:42px;height:42px;border-color:#66e0ad;box-shadow:0 0 0 7px rgba(102,224,173,.08),0 10px 30px rgba(0,0,0,.4)}.map-legend{position:absolute;left:14px;bottom:14px;z-index:4;display:flex;gap:6px;flex-wrap:wrap;max-width:70%}.map-legend span{font-size:7px;padding:5px 7px;border-radius:999px;background:rgba(5,14,24,.78);border:1px solid rgba(255,255,255,.1);color:#b5c6d6}.map-next-label{position:absolute;z-index:4;right:14px;bottom:14px;max-width:180px;padding:9px 10px;border-radius:13px;background:rgba(5,14,24,.83);border:1px solid rgba(102,224,173,.16);font-size:8px;color:#bfe8d5}.map-next-label b{display:block;color:#eafff7;font-size:9px;margin-bottom:3px}
@media(max-width:600px){.next-objective{grid-template-columns:1fr}.next-level{width:100%;height:46px;display:flex;gap:5px}.build-head{grid-template-columns:72px 1fr auto}.build-head img{width:72px;height:72px}.build-meta{grid-template-columns:1fr}.paldea-map{min-height:680px}.moves-grid{grid-template-columns:1fr}}
'''
if '/* Journey 1.8' not in s:s=s.replace('</style>',css+'\n</style>',1)
js=r'''
// Journey 1.8 — researched story builds and next-objective guidance.
const SV_ROUTE_POS=[[28,72],[64,72],[72,60],[23,52],[17,42],[78,49],[78,30],[71,26],[21,34],[32,22],[48,45],[61,17],[27,31],[22,82],[48,12],[16,18],[31,13],[78,17]];
const SV_COUNTERS={Bug:['Fire','Flying','Rock'],Rock:['Water','Grass','Fighting','Ground','Steel'],Grass:['Fire','Ice','Poison','Flying','Bug'],Flying:['Electric','Ice','Rock'],Dark:['Fighting','Bug','Fairy'],Electric:['Ground'],Fire:['Water','Ground','Rock'],Steel:['Fire','Fighting','Ground'],Water:['Electric','Grass'],Poison:['Ground','Psychic'],Normal:['Fighting'],Ghost:['Ghost','Dark'],Ground:['Water','Grass','Ice'],Psychic:['Bug','Ghost','Dark'],Ice:['Fire','Fighting','Rock','Steel'],Fairy:['Poison','Steel'],Dragon:['Ice','Dragon','Fairy'],Fighting:['Flying','Psychic','Fairy']};
const SV_BUILD_FAMILY={906:908,907:908,908:908,909:911,910:911,911:911,912:914,913:914,914:914,935:936,936:936,821:823,822:823,823:823,940:941,941:941,129:130,130:130,194:980,980:980,928:930,929:930,930:930};
const SV_BUILDS={
908:{name:'Meowscarada',role:'Atacante físico veloz',nature:'Jolly',ability:'Overgrow / Protean',item:'Focus Sash ou Choice Band',moves:['Flower Trick','Knock Off','Play Rough','U-turn'],note:'Priorize Flower Trick como STAB confiável; cobertura Dark/Fairy ajuda bastante na campanha.'},
911:{name:'Skeledirge',role:'Atacante especial resistente',nature:'Modest',ability:'Blaze',item:'Wise Glasses ou Throat Spray',moves:['Torch Song','Will-O-Wisp','Hex','Shadow Ball / Fire Blast'],note:'Torch Song aumenta o Sp. Atk durante a luta; Will-O-Wisp + Hex é uma combinação forte para chefes.'},
914:{name:'Quaquaval',role:'Atacante físico de snowball',nature:'Adamant',ability:'Moxie',item:'Muscle Band',moves:['Aqua Step','Close Combat','Aqua Jet','Swords Dance'],note:'Aqua Step acelera enquanto causa dano; Moxie ajuda a limpar equipes depois do primeiro nocaute.'},
936:{name:'Armarouge / Ceruledge',role:'Slot Fire por versão',nature:'Modest (Armarouge) / Adamant (Ceruledge)',ability:'Flash Fire',item:'Wise Glasses / Muscle Band',moves:['Armor Cannon ou Bitter Blade','Psychic/Psycho Cut','Calm Mind/Swords Dance','Flamethrower/Flare Blitz'],note:'Em Scarlet, prefira Armarouge; em Violet, Ceruledge. O slot mantém cobertura Fire e uma segunda tipagem útil.'},
823:{name:'Corviknight',role:'Tanque físico',nature:'Impish',ability:'Pressure',item:'Muscle Band',moves:['Steel Wing','Drill Peck','Iron Defense','Hone Claws'],note:'Ótimo pivô defensivo durante a história e útil contra Grass, Bug, Ice e Fairy.'},
941:{name:'Kilowattrel',role:'Atacante especial veloz',nature:'Timid',ability:'Wind Power',item:'Wise Glasses',moves:['Electro Ball','Air Slash / Discharge','Thunderbolt','Agility'],note:'Velocidade alta e cobertura Electric/Flying tornam Kilowattrel excelente em vários confrontos da rota.'},
130:{name:'Gyarados',role:'Sweeper físico',nature:'Adamant',ability:'Intimidate',item:'Muscle Band',moves:['Crunch','Aqua Tail','Earthquake','Dragon Dance'],note:'Intimidate facilita entradas seguras e Dragon Dance pode decidir batalhas longas.'},
980:{name:'Clodsire',role:'Defensor especial / utilidade',nature:'Careful',ability:'Water Absorb',item:'Clear Amulet',moves:['Megahorn','Poison Jab / Toxic','Earthquake','Yawn'],note:'Water Absorb cobre uma fraqueza importante do time e Yawn cria espaço para trocar ou preparar outro membro.'},
930:{name:'Arboliva',role:'Atacante especial bulky',nature:'Modest',ability:'Seed Sower',item:'Wise Glasses',moves:['Giga Drain / Leech Seed','Petal Dance / Terrain Pulse','Mirror Coat','Hyper Voice'],note:'Seed Sower sustenta o time com Grassy Terrain enquanto Arboliva pressiona pelo lado especial.'}
};
function svNextIndex(){const d=new Set(state.journey.sv.done||[]);for(let i=1;i<=SV_ROUTE.length;i++)if(!d.has(i))return i;return 0}
function svProgressPct(){return Math.round(((state.journey.sv.done||[]).length/SV_ROUTE.length)*100)}
function svNextCard(){const n=svNextIndex();if(!n)return `<div class="next-objective"><div><div class="kicker">Rota principal concluída</div><h3>18 objetivos completos</h3><p>Agora você pode seguir para o fechamento das histórias e conteúdo final.</p><div class="journey-progressline"><i style="width:100%"></i></div></div><div class="next-level">✓</div></div>`;const r=SV_ROUTE[n-1],c=SV_COUNTERS[r[3]]||[];return `<div class="next-objective"><div><div class="kicker">Próximo objetivo · ${n}/18</div><h3>${r[0]}</h3><p>${r[1]==='gym'?'Ginásio':r[1]==='titan'?'Titã':'Team Star'} · tipo ${r[3]} · siga a ordem sugerida porque os chefes não escalam automaticamente com o jogador.</p><div class="prep-row">${c.map(x=>`<span class="prep-chip">✓ ${x}</span>`).join('')}</div><div class="journey-progressline"><i style="width:${svProgressPct()}%"></i></div></div><div class="next-level"><div>Lv.${r[2]}<small>ALVO</small></div></div></div>`}
function teamOwnedV18(id){const family=SV_BUILD_FAMILY[id]||id;return !!state.global[id]||!!state.global[family]||instancesForSpecies(id).length>0||instancesForSpecies(family).length>0}
function openJourneyBuild(id){const target=SV_BUILD_FAMILY[id]||id,b=SV_BUILDS[target];if(!b){premiumToast('Build detalhada ainda não disponível para este estágio');return}document.getElementById('journeyBuild')?.remove();const el=document.createElement('div');el.id='journeyBuild';el.className='build-sheet';el.onclick=e=>{if(e.target===el)el.remove()};el.innerHTML=`<div class="build-card"><div class="build-head">${pokemonImageHTML(target,'')}<div><h3>${b.name}</h3><p>${b.role} · build de campanha</p></div><button class="btn" onclick="document.getElementById('journeyBuild').remove()">Fechar</button></div><div class="build-meta"><div><small>Nature</small><b>${b.nature}</b></div><div><small>Ability</small><b>${b.ability}</b></div><div><small>Item</small><b>${b.item}</b></div></div><h4 style="margin:0 0 8px">Golpes recomendados</h4><div class="moves-grid">${b.moves.map((m,i)=>`<div class="move"><small>Slot ${i+1}</small><b>${m}</b></div>`).join('')}</div><div class="build-note">${b.note}</div><div class="research-note">Build voltada à história, baseada em guias de Scarlet/Violet. <a href="https://game8.co/games/Pokemon-Scarlet-Violet/archives/393731">Equipe de campanha</a> · <a href="https://game8.co/games/Pokemon-Scarlet-Violet/archives/394479">ordem por nível</a>.</div></div>`;document.body.appendChild(el)}
const journeyRouteV17=journeyRoute;journeyRoute=function(){return svNextCard()+journeyRouteV17()}
const journeyTeamV17=journeyTeam;journeyTeam=function(){let j=state.journey.sv,ids=SV_TEAMS[j.starter][j.phase];return `${svNextCard()}<div class="starter-row">${['sprigatito','fuecoco','quaxly'].map(x=>`<button class="${j.starter===x?'active':''}" onclick="setJourneyStarter('${x}')">${x[0].toUpperCase()+x.slice(1)}</button>`).join('')}</div><div class="phase-row">${[['early','Início'],['mid','Mid game'],['late','Late game']].map(x=>`<button class="${j.phase===x[0]?'active':''}" onclick="setJourneyPhase('${x[0]}')">${x[1]}</button>`).join('')}</div><div class="team-grid">${ids.map(id=>`<div class="team-poke" onclick="openJourneyBuild(${id})"><span class="owned-dot ${teamOwnedV18(id)?'yes':''}"></span>${pokemonImageHTML(id,'')}<b>#${String(id).padStart(4,'0')}</b><small style="color:#8fa5bc">Ver build de campanha</small></div>`).join('')}</div><p style="font-size:9px;color:#8197ad;line-height:1.5;margin-top:14px">O ponto verde indica que o Pokémon (ou sua evolução-alvo) já aparece na sua coleção. Toque em qualquer integrante para abrir Nature, Ability, item e moveset recomendados.</p>`}
function journeyMap(){const n=svNextIndex();return `${svNextCard()}<div class="paldea-map"><div class="paldea-land"></div><div class="paldea-center"></div><button class="btn map-full" onclick="toggleJourneyMapFull()">⛶ Tela cheia</button>${SV_ROUTE.map((r,i)=>{const p=SV_ROUTE_POS[i],num=i+1,done=(state.journey.sv.done||[]).includes(num);return `<button class="geo-node ${r[1]} ${done?'done':''} ${n===num?'next':''}" style="left:${p[0]}%;top:${p[1]}%" onclick="premiumToast('${num}. ${r[0]} · Lv.${r[2]}')">${done?'✓':num}</button>`}).join('')}<div class="map-legend"><span>● Ginásio</span><span>● Titã</span><span>● Team Star</span></div>${n?`<div class="map-next-label"><b>Próximo: ${n}. ${SV_ROUTE[n-1][0]}</b>Lv.${SV_ROUTE[n-1][2]} · ${SV_ROUTE[n-1][3]}</div>`:''}</div><p style="font-size:9px;color:#8197ad;line-height:1.5">Mapa esquemático próprio do Living Dex Hub, organizado para orientação de rota. Os pontos representam a posição aproximada das etapas em Paldea e destacam automaticamente seu próximo objetivo.</p>`}
const toggleJourneyStepV17=toggleJourneyStep;toggleJourneyStep=function(n){toggleJourneyStepV17(n);setTimeout(()=>{if(document.getElementById('journeyShell')?.dataset.tab==='map')renderJourney('map')},0)}
const androidHandleBackV18=androidHandleBack;androidHandleBack=function(){const b=document.getElementById('journeyBuild');if(b){b.remove();return true}return androidHandleBackV18()}
'''
s=s.replace('</body>','<script>'+js+'</script>\n</body>',1)
p.write_text(s,encoding='utf-8')
print('Journey 1.8 applied')
