from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
HTML=ROOT/'app'/'src'/'main'/'assets'/'index.html'
html=HTML.read_text(encoding='utf-8')
if 'living-dex-premium" content="1.6"' not in html: html=html.replace('</head>','<meta name="living-dex-premium" content="1.6"/>\n</head>',1)
html=html.replace('Core 1.0 • UI 1.5 • Offline','Core 1.0 • Premium 1.6 • Offline',1)
css=r'''
/* Living Dex Hub Premium 1.6 — focused Home + polished native-app feel */
:root{--premium-bg:#07111f;--premium-panel:rgba(13,27,46,.82);--premium-line:rgba(148,180,215,.15);--premium-text:#f5f9ff;--premium-muted:#93a8c0;--premium-accent:#72d5ff;--premium-green:#66e0ad;--premium-shadow:0 18px 55px rgba(0,0,0,.28)}
html{background:var(--premium-bg)}body{background:radial-gradient(900px 520px at 12% -12%,rgba(56,189,248,.12),transparent 62%),radial-gradient(760px 520px at 100% 0%,rgba(99,102,241,.11),transparent 62%),linear-gradient(180deg,#07111f 0%,#091522 48%,#07111f 100%);color:var(--premium-text);letter-spacing:.01em}
.card,.game,.globalbox>.card,.ring-card,.metric,.backup-guide{border-color:var(--premium-line)!important;background:linear-gradient(180deg,rgba(18,35,56,.88),rgba(10,23,40,.92))!important;box-shadow:var(--premium-shadow);backdrop-filter:blur(18px);-webkit-backdrop-filter:blur(18px)}
.card,.game,.metric,.btn,.mnav-item,.mobile-more button,.pk{transition:transform .18s ease,box-shadow .22s ease,border-color .22s ease,background .22s ease,opacity .2s ease}.btn{border-radius:14px!important;font-weight:750;min-height:44px;box-shadow:inset 0 1px 0 rgba(255,255,255,.06)}.btn:active,.mnav-item:active,.mobile-more button:active,.game:active{transform:scale(.975)}
.btn.primary,.btn.green{background:linear-gradient(135deg,#2dbbe8,#4d7cff)!important;border-color:rgba(115,208,255,.38)!important;color:white!important;box-shadow:0 10px 28px rgba(47,132,255,.2)}.search,input,select,textarea{background:rgba(5,15,28,.72)!important;border-color:rgba(148,180,215,.16)!important;border-radius:14px!important;color:var(--premium-text)!important}
.statusbar{background:rgba(5,13,24,.72)!important;border-top-color:rgba(148,180,215,.1)!important;backdrop-filter:blur(16px)}.mobile-nav{background:rgba(6,15,27,.9)!important;border-top:1px solid rgba(148,180,215,.13)!important;backdrop-filter:blur(22px);-webkit-backdrop-filter:blur(22px);box-shadow:0 -14px 38px rgba(0,0,0,.28)}.mnav-item{border-radius:15px!important}.mnav-item.active{background:linear-gradient(180deg,rgba(72,175,255,.18),rgba(72,175,255,.06))!important;color:#dff5ff!important}.mobile-more{background:rgba(8,20,35,.96)!important;border-color:rgba(148,180,215,.15)!important;box-shadow:0 -22px 70px rgba(0,0,0,.42)!important;backdrop-filter:blur(24px)}.mobile-more button{border-radius:16px!important;background:rgba(255,255,255,.025)!important}
.view.active{animation:premiumViewIn .28s cubic-bezier(.2,.7,.2,1)}@keyframes premiumViewIn{from{opacity:.35;transform:translateY(8px)}to{opacity:1;transform:none}}.pk{border-radius:18px!important;overflow:hidden}.quick-catch{border-radius:12px!important;box-shadow:0 8px 24px rgba(0,0,0,.34)!important}
#home>.scope-note,#home>.hero,#home>.progress-zone,#home>.section,#home>.game-progress-list,#home>.games{display:none!important}#home .home-current-shell{display:block!important;max-width:860px;margin:0 auto;padding:4px 0 24px}.home-current-head{display:flex;align-items:flex-end;justify-content:space-between;gap:18px;margin:6px 0 18px;padding:0 2px}.home-current-head .eyebrow{font-size:11px;text-transform:uppercase;letter-spacing:.16em;color:#72d5ff;font-weight:850}.home-current-head h1{font-size:clamp(27px,6.5vw,42px);line-height:1.02;margin:7px 0 0;letter-spacing:-.035em}.home-current-head p{color:var(--premium-muted);max-width:540px;margin:8px 0 0;font-size:12px;line-height:1.55}
.playing-card{position:relative;overflow:hidden;border:1px solid var(--premium-line);border-radius:28px;background:radial-gradient(420px 250px at 90% 5%,rgba(84,201,255,.18),transparent 62%),linear-gradient(145deg,rgba(18,40,65,.96),rgba(10,23,40,.98));box-shadow:0 24px 70px rgba(0,0,0,.32);padding:22px}.playing-card:before{content:"";position:absolute;width:220px;height:220px;border-radius:50%;right:-70px;top:-90px;border:34px solid rgba(255,255,255,.035)}.playing-top{position:relative;display:flex;align-items:flex-start;justify-content:space-between;gap:12px}.playing-badge{display:inline-flex;align-items:center;gap:7px;border:1px solid rgba(102,224,173,.22);background:rgba(102,224,173,.08);color:#b8f7db;border-radius:999px;padding:7px 10px;font-size:10px;font-weight:850}.playing-badge i{width:7px;height:7px;border-radius:50%;background:#66e0ad;box-shadow:0 0 15px rgba(102,224,173,.85)}.playing-platform{font-size:10px;color:#9db0c5;border:1px solid rgba(148,180,215,.13);border-radius:999px;padding:7px 10px;background:rgba(255,255,255,.025)}
.playing-name{position:relative;margin-top:28px;max-width:620px}.playing-name .version{font-size:12px;color:#72d5ff;font-weight:800;margin-bottom:5px}.playing-name h2{font-size:clamp(29px,8vw,46px);letter-spacing:-.04em;margin:0 0 8px;line-height:1}.playing-name p{margin:0;color:#a7b8ca;font-size:12px;line-height:1.55;max-width:520px}.playing-progress{position:relative;margin-top:24px;display:grid;grid-template-columns:1fr auto;align-items:end;gap:14px}.playing-progress .label{font-size:10px;color:#8ea2b8;margin-bottom:8px}.playing-progress .value{font-size:13px;font-weight:800}.premium-progress{height:8px;border-radius:999px;background:rgba(255,255,255,.055);overflow:hidden;border:1px solid rgba(255,255,255,.04)}.premium-progress i{display:block;height:100%;border-radius:inherit;background:linear-gradient(90deg,#4fd5ff,#6c8cff,#66e0ad)}.playing-percent{font-size:28px;font-weight:900;letter-spacing:-.04em}.playing-actions{position:relative;display:grid;grid-template-columns:1fr auto;gap:10px;margin-top:22px}.playing-actions .btn{min-height:50px}
.empty-current{border:1px solid var(--premium-line);border-radius:28px;padding:28px;background:linear-gradient(155deg,rgba(17,34,55,.94),rgba(9,21,37,.97));box-shadow:var(--premium-shadow);text-align:left}.empty-current .icon{width:54px;height:54px;border-radius:18px;display:grid;place-items:center;font-size:24px;background:linear-gradient(135deg,rgba(72,175,255,.18),rgba(102,224,173,.11));border:1px solid rgba(114,213,255,.18);margin-bottom:18px}.empty-current h2{font-size:27px;margin:0 0 8px;letter-spacing:-.03em}.empty-current p{color:#93a8c0;line-height:1.6;font-size:12px;margin:0 0 18px;max-width:570px}
.game{position:relative;border-radius:22px!important;padding-bottom:68px!important;overflow:hidden}.game.playing{border-color:rgba(102,224,173,.36)!important;box-shadow:0 18px 52px rgba(0,0,0,.28),0 0 0 1px rgba(102,224,173,.08) inset!important}.game.playing:after{content:"Jogando agora";position:absolute;right:12px;top:12px;padding:6px 9px;border-radius:999px;background:rgba(102,224,173,.11);border:1px solid rgba(102,224,173,.22);color:#bdf6dc;font-size:9px;font-weight:850}.game-active-btn{position:absolute;left:12px;right:12px;bottom:12px;z-index:3;min-height:42px;border-radius:13px;border:1px solid rgba(148,180,215,.15);background:rgba(7,17,31,.72);color:#b9c9da;font-size:10px;font-weight:850;cursor:pointer}.game-active-btn.active{background:linear-gradient(135deg,rgba(48,182,214,.2),rgba(61,126,255,.16));border-color:rgba(102,224,173,.28);color:#dffdf1}.premium-toast{position:fixed;left:50%;bottom:calc(90px + env(safe-area-inset-bottom));transform:translate(-50%,18px);z-index:9999;padding:10px 14px;border-radius:14px;background:rgba(10,23,39,.95);border:1px solid rgba(114,213,255,.18);box-shadow:0 16px 44px rgba(0,0,0,.35);font-size:11px;font-weight:750;color:#eaf8ff;opacity:0;pointer-events:none;transition:.22s ease}.premium-toast.show{opacity:1;transform:translate(-50%,0)}
@media(max-width:700px){.home-current-head{align-items:flex-start;flex-direction:column}.playing-card{border-radius:24px;padding:18px}.playing-name{margin-top:24px}.playing-actions{grid-template-columns:1fr}.playing-actions .btn{width:100%}.playing-percent{font-size:24px}.game{border-radius:19px!important}}
'''
if 'Living Dex Hub Premium 1.6' not in html: html=html.replace('</style>',css+'\n</style>',1)
old="function gameCard(g){return `<div class=\"game\" onclick=\"openGame('${g.id}')\"><div class=\"plat\">${g.platform}</div><h3>${g.name}</h3><div class=\"tiny\">${g.dex} Pokédex</div><span class=\"pill\">${g.count} entradas</span><div class=\"orb\"></div></div>`}"
new="function gameCard(g){const active=state.activeGameId===g.id;return `<div class=\"game ${active?'playing':''}\" onclick=\"openGame('${g.id}')\"><div class=\"plat\">${g.platform}</div><h3>${g.name}</h3><div class=\"tiny\">${g.dex} Pokédex • ${selectedVersion(g.id)||'versão padrão'}</div><span class=\"pill\">${g.count} entradas</span><button type=\"button\" class=\"game-active-btn ${active?'active':''}\" onclick=\"event.stopPropagation();setActiveGame('${g.id}')\">${active?'✓ Jogo atual':'Definir como jogo atual'}</button><div class=\"orb\"></div></div>`}"
if old not in html: raise SystemExit('gameCard original não encontrado')
html=html.replace(old,new,1)
old_rg="function renderGames(){document.getElementById('homeGames').innerHTML=GAMES.slice(0,6).map(gameCard).join('');document.getElementById('gamesGrid').innerHTML=GAMES.map(gameCard).join('')}"
new_rg="function renderGames(){document.getElementById('homeGames').innerHTML=GAMES.slice(0,6).map(gameCard).join('');document.getElementById('gamesGrid').innerHTML=GAMES.map(gameCard).join('');renderActiveGameHome()}"
if old_rg not in html: raise SystemExit('renderGames original não encontrado')
html=html.replace(old_rg,new_rg,1)
js=r'''
// Living Dex Hub Premium 1.6 — focused Home continuity and persistent current game.
state.activeGameId=state.activeGameId||'';
function premiumToast(msg){let t=document.getElementById('premiumToast');if(!t){t=document.createElement('div');t.id='premiumToast';t.className='premium-toast';document.body.appendChild(t)}t.textContent=msg;t.classList.remove('show');requestAnimationFrame(()=>t.classList.add('show'));clearTimeout(premiumToast._t);premiumToast._t=setTimeout(()=>t.classList.remove('show'),1800)}
function setActiveGame(id){if(!GAMES.some(g=>g.id===id))return;state.activeGameId=id;persist();renderGames();renderActiveGameHome();const g=GAMES.find(x=>x.id===id);premiumToast(`${g.name} definido como jogo atual`)}
function activeGameProgress(g){if(!g)return {caught:0,total:0,pct:0};const ids=new Set();Object.entries(state.games||{}).forEach(([k,v])=>{if(v&&k.startsWith(g.id+':'))ids.add(Number(k.split(':').pop()))});const caught=ids.size,total=Number(g.count||0),pct=total?Math.min(100,Math.round((caught/total)*100)):0;return {caught,total,pct}}
function continueActiveGame(){const id=state.activeGameId;if(id)openGame(id);else go('games')}
function renderActiveGameHome(){const home=document.getElementById('home');if(!home)return;let shell=home.querySelector('.home-current-shell');if(!shell){shell=document.createElement('div');shell.className='home-current-shell';home.prepend(shell)}const g=GAMES.find(x=>x.id===state.activeGameId);if(!g){shell.innerHTML=`<div class="home-current-head"><div><div class="eyebrow">Início</div><h1>Continue sua jornada</h1><p>O Início agora mostra apenas o jogo que você está jogando no momento. Defina um jogo atual na biblioteca para voltar a ele com um toque.</p></div></div><div class="empty-current"><div class="icon">◉</div><h2>Nenhum jogo atual</h2><p>Abra Jogos e escolha “Definir como jogo atual”. Essa escolha fica salva no aparelho e passa a ocupar sua tela inicial.</p><button class="btn primary" onclick="go('games')">Escolher jogo atual</button></div>`;return}const p=activeGameProgress(g),version=selectedVersion(g.id)||'Versão padrão';shell.innerHTML=`<div class="home-current-head"><div><div class="eyebrow">Jogando agora</div><h1>Continue de onde parou</h1><p>Sem atalhos duplicados: sua tela inicial ficou focada exclusivamente na jornada que está ativa agora.</p></div></div><button class="btn" onclick="go('games')">Trocar jogo</button></div><div class="playing-card"><div class="playing-top"><span class="playing-badge"><i></i> Jogo atual</span><span class="playing-platform">${g.platform}</span></div><div class="playing-name"><div class="version">${version}</div><h2>${g.name}</h2><p>${g.dex} Pokédex. Continue registrando sua coleção exatamente na versão selecionada.</p></div><div class="playing-progress"><div><div class="label">Progresso registrado neste jogo</div><div class="value">${p.caught}${p.total?' / '+p.total:''} Pokémon</div><div class="premium-progress" style="margin-top:9px"><i style="width:${p.pct}%"></i></div></div><div class="playing-percent">${p.pct}%</div></div><div class="playing-actions"><button class="btn primary" onclick="continueActiveGame()">Continuar ${version}</button><button class="btn" onclick="go('games')">Ver biblioteca</button></div></div>`}
setTimeout(()=>renderActiveGameHome(),0);
'''
marker='// Living Dex Hub Premium 1.6 — focused Home continuity and persistent current game.'
if marker not in html: html=html.replace('function androidHandleBack(){',js+'\nfunction androidHandleBack(){',1)
old_go="function go(v){ui12Ensure();syncMobileNav(v);"
new_go="function go(v){ui12Ensure();syncMobileNav(v);if(v==='home')renderActiveGameHome();"
if old_go not in html: raise SystemExit('go() não encontrado')
html=html.replace(old_go,new_go,1)
required=['living-dex-premium" content="1.6"',marker,'state.activeGameId','function setActiveGame','function renderActiveGameHome','Definir como jogo atual','Continue de onde parou','premium-toast','game-active-btn']
missing=[x for x in required if x not in html]
if missing: raise SystemExit('Premium 1.6 incompleto: '+str(missing))
HTML.write_text(html,encoding='utf-8')
print(f'Premium 1.6 aplicado: {HTML} • {HTML.stat().st_size} bytes')
