from pathlib import Path
p=Path(__file__).resolve().parents[1]/'app'/'src'/'main'/'assets'/'index.html'
s=p.read_text(encoding='utf-8')
if 'living-dex-reference-ui" content="4.0"' not in s:
    s=s.replace('</head>','<meta name="living-dex-reference-ui" content="4.0"/>\n</head>',1)
css=r'''
/* Living Dex Hub 4.0 — approved light reference translated into one complete design system. */
:root{
 --r4-bg:#f7f8fb;--r4-bg2:#fff;--r4-card:#fff;--r4-text:#17213c;--r4-muted:#7f8aa2;
 --r4-line:#edf0f5;--r4-red:#ff5555;--r4-red2:#ff625c;--r4-blue:#5398ff;--r4-green:#22cc94;
 --r4-soft-red:#fff0f0;--r4-soft-blue:#edf5ff;--r4-shadow:0 12px 38px rgba(35,48,79,.09);
 --r4-shadow2:0 5px 18px rgba(35,48,79,.07);--r4-r:22px;--r4-r-lg:30px;
}
html,body{background:var(--r4-bg)!important;color:var(--r4-text)!important}body{font-family:Inter,system-ui,-apple-system,"Segoe UI",sans-serif!important;background-image:radial-gradient(circle at 105% 3%,rgba(255,85,85,.16),transparent 18%),radial-gradient(circle at -6% 30%,rgba(83,152,255,.10),transparent 18%)!important;background-attachment:fixed!important}.wrap{max-width:1080px!important;padding:12px 16px calc(104px + env(safe-area-inset-bottom))!important}
/* Remove every old shell. */
.top,.appbar:not(.v4-appbar),.nav,.tabs,.statusbar,.scope-note,.v3-appbar,.data-pack-note,.sync-note,.home-current-head,.hero,.home-intro,.home-heading,.home-kicker,.home-lead{display:none!important}
/* Header from approved reference */
.v4-appbar{display:flex;align-items:center;justify-content:space-between;gap:12px;min-height:72px;margin:0 0 12px;padding:4px 2px}.v4-brand{display:flex;align-items:center;gap:11px}.v4-ball{width:46px;height:46px;border-radius:50%;position:relative;overflow:hidden;border:1.5px solid #d9dee8;background:linear-gradient(#ff5959 0 47%,#222b3e 47% 53%,#fff 53%);box-shadow:0 5px 12px rgba(31,42,68,.12)}.v4-ball:before{content:"";position:absolute;left:50%;top:50%;width:14px;height:14px;border-radius:50%;background:#fff;border:4px solid #222b3e;transform:translate(-50%,-50%)}.v4-brand-text b{display:block;font-size:24px;letter-spacing:-.045em;line-height:1}.v4-brand-text b em{font-style:normal;color:var(--r4-red)}.v4-brand-text small{display:block;margin-top:7px;font-size:8px;letter-spacing:.28em;text-transform:uppercase;color:#aab2c2}.v4-avatar{width:42px;height:42px;border-radius:50%;background:linear-gradient(145deg,#e8f4ff,#fff0e8);border:2px solid #fff;box-shadow:var(--r4-shadow2);display:grid;place-items:center;position:relative;overflow:hidden}.v4-avatar img{width:88%;height:88%;object-fit:contain}.v4-avatar:after{content:"";width:9px;height:9px;background:#14d69a;border:2px solid #fff;border-radius:50%;position:absolute;right:0;bottom:1px}
/* Page titles */
.section-head h1,.section-head h2,.section h2{color:var(--r4-text)!important;font-size:24px!important;letter-spacing:-.035em!important}.section-head p,.section>p,.ui24-explainer-hidden{display:none!important}.eyebrow,.kicker{color:var(--r4-red)!important}
/* Universal cards */
.card,.game,.metric,.ring-card,.family-card,.quest,.route,.queue-item,.callout,.playing-card,.empty-current,.home-journey-summary,.journey-card,.journey-panel,.pk,.globalbox>.card,#settings .card,#storage .card,#planner .card,#forms .card,#families .card{background:#fff!important;color:var(--r4-text)!important;border:1px solid var(--r4-line)!important;border-radius:var(--r4-r)!important;box-shadow:var(--r4-shadow2)!important;backdrop-filter:none!important}.card h1,.card h2,.card h3,.game h3,.journey-card h2,.journey-card h3,.playing-card h2,.sheet h2,.sheet h3,.modal h2,.modal h3{color:var(--r4-text)!important}.tiny,.muted,.card p,.card small,.game .tiny,.journey-card p,.journey-card small,.journey-panel p,.journey-panel small{color:var(--r4-muted)!important}
/* Home hero mirrors approved reference */
#home{padding-top:0!important}#home .home-current-shell{max-width:none!important;margin:0!important;padding:0!important}#home .playing-card{min-height:430px!important;padding:26px 28px!important;border-radius:32px!important;border:0!important;overflow:hidden!important;position:relative!important;background:linear-gradient(180deg,rgba(18,37,59,.08),rgba(16,29,50,.86)),url('assets/maps/paldea-route.svg') center/cover no-repeat!important;color:#fff!important;box-shadow:0 18px 42px rgba(35,48,79,.17)!important}#home .playing-card:before{content:""!important;position:absolute!important;inset:0!important;background:linear-gradient(180deg,rgba(255,255,255,.02) 18%,rgba(9,18,33,.06) 44%,rgba(10,20,38,.86) 100%)!important;width:auto!important;height:auto!important;border:0!important;border-radius:0!important;right:auto!important;top:auto!important;opacity:1!important}.playing-top,.playing-name,.playing-progress,.playing-actions{position:relative!important;z-index:2!important}.playing-badge{background:var(--r4-red)!important;color:#fff!important;border:0!important;border-radius:999px!important;padding:9px 13px!important;font-size:10px!important}.playing-badge i{background:#fff!important;box-shadow:none!important}.playing-platform{background:rgba(255,255,255,.14)!important;border:1px solid rgba(255,255,255,.25)!important;color:#fff!important;border-radius:999px!important;padding:8px 11px!important}.playing-name{margin-top:160px!important}.playing-name .version{color:#fff!important;font-size:12px!important}.playing-name h2{color:#fff!important;font-size:clamp(32px,8vw,49px)!important;letter-spacing:-.045em!important;text-shadow:0 2px 10px rgba(0,0,0,.18)}.playing-name p{display:none!important}.playing-progress{margin-top:16px!important;grid-template-columns:1fr auto!important}.playing-progress .label{display:none!important}.playing-progress .value,.playing-percent{color:#fff!important}.premium-progress{background:rgba(255,255,255,.34)!important;border:0!important;height:8px!important}.premium-progress i{background:var(--r4-red)!important}.playing-actions{margin-top:20px!important}.playing-actions .btn{background:linear-gradient(135deg,var(--r4-red),#ff6660)!important;border:0!important;color:#fff!important;min-height:58px!important;font-size:16px!important;border-radius:17px!important;box-shadow:0 10px 25px rgba(255,85,85,.28)!important}
/* Journey preview becomes three cards like reference */
#home .home232-journey,#home .home-journey-summary{margin-top:24px!important;background:transparent!important;border:0!important;box-shadow:none!important;padding:0!important}#home .home232-journey:before,#home .home-journey-summary:before{content:'Jornada';display:block;font-size:22px;font-weight:850;letter-spacing:-.035em;margin:0 0 12px;color:var(--r4-text)}#home .home232-journey .card,#home .home-journey-summary .card{box-shadow:var(--r4-shadow2)!important}#home .home232-journey .btn,#home .home-journey-summary .btn{background:transparent!important;border:0!important;color:var(--r4-red)!important;box-shadow:none!important}
/* Library */
.nav23-general-switch{position:sticky!important;top:8px!important;z-index:22!important;background:#fff!important;border:1px solid var(--r4-line)!important;border-radius:18px!important;padding:5px!important;box-shadow:var(--r4-shadow2)!important}.nav23-general-switch button{color:#8d96aa!important;border-radius:14px!important;min-height:44px!important}.nav23-general-switch button.active{background:var(--r4-soft-red)!important;color:var(--r4-red)!important;box-shadow:none!important}#gamesGrid.nav23-compact-library{gap:12px!important}.game{min-height:184px!important;padding:16px!important;overflow:hidden!important}.game .plat{color:#9ba4b5!important}.game h3{font-size:16px!important;color:var(--r4-text)!important}.game .pill{background:#f3f5f8!important;color:#7b8598!important;border:0!important}.game .orb{opacity:.07!important;border-color:var(--r4-red)!important}.game.playing{border-color:#ffd6d6!important}.game.playing:after{background:var(--r4-soft-red)!important;color:var(--r4-red)!important;border:0!important}.nav23-game-actions .game-active-btn,.nav23-game-actions .nav23-open-dex{border-radius:13px!important}.nav23-game-actions .nav23-open-dex{background:var(--r4-red)!important;color:#fff!important;border:0!important}.game-active-btn{background:#f7f8fa!important;color:#6c768a!important;border:0!important}.game-active-btn.active{background:#eafaf4!important;color:#12966a!important}
/* Dex exactly in light visual language */
#dexCard,.globalbox{background:transparent!important;border:0!important;box-shadow:none!important}.toolbar,.filters{position:sticky!important;top:5px!important;z-index:18!important;background:rgba(255,255,255,.94)!important;border:1px solid var(--r4-line)!important;border-radius:20px!important;padding:9px!important;box-shadow:var(--r4-shadow2)!important;backdrop-filter:blur(14px)!important}.search,input,select,textarea{background:#f7f8fb!important;color:var(--r4-text)!important;border:1px solid #e8ebf1!important;border-radius:14px!important;min-height:44px!important}.search:focus,input:focus,select:focus,textarea:focus{border-color:#ffc4c4!important;box-shadow:0 0 0 3px rgba(255,85,85,.08)!important}.dexgrid{gap:10px!important}.pk{min-height:145px!important;padding:9px 7px!important}.pk img{filter:none!important;transition:transform .22s ease!important}.pk:active img{transform:scale(.93)!important}.pk h4{color:var(--r4-text)!important}.pk .num,.pk .small,.pk small{color:#929bad!important}.pk.caught{background:#f6fffb!important;border-color:#d8f5e9!important}.quick-catch{background:#fff!important;color:var(--r4-red)!important;border:1px solid #eceff4!important;box-shadow:0 4px 10px rgba(35,48,79,.09)!important}.quick-catch.is-owned{background:#eafaf4!important;color:#139c6c!important;border-color:#d2f0e3!important}
/* Journey full */
.journey-shell,.journey-view{background:var(--r4-bg)!important;color:var(--r4-text)!important}.journey-card,.journey-panel{padding:18px!important}.journey-map-wrap,.journey-map{border-radius:22px!important;border:1px solid var(--r4-line)!important;overflow:hidden!important}.journey-step,.journey-route-item,.route,.journey-team-card,.journey-build-card{background:#fff!important;border:1px solid var(--r4-line)!important;border-radius:18px!important;box-shadow:var(--r4-shadow2)!important;color:var(--r4-text)!important}.journey-progress,.journey-route-progress{background:#eceff4!important}.journey-progress>i,.journey-route-progress>i{background:var(--r4-red)!important}.journey-card .btn.primary,.journey-panel .btn.primary{background:var(--r4-red)!important;color:#fff!important;border:0!important}
/* Families / planner / forms / storage / settings */
.family-dashboard,.family-list,.planner,.route-grid{gap:12px!important}.family-card,.quest,.route,.queue-item,.callout{background:#fff!important}.metric{background:#fff!important}.metric .v{color:var(--r4-text)!important}.ring{background:conic-gradient(var(--r4-red) var(--p,0%),#edf0f5 0)!important}.ring:before{background:#fff!important}.ring-inner b{color:var(--r4-text)!important}.pill,.tag{border-radius:999px!important}.settings label,#settings label{color:#737d91!important}
/* Profile and modal */
.sheet,.modal{background:rgba(31,40,61,.25)!important;backdrop-filter:blur(10px)!important}.sheet>div,.modal>div,.sheet{color:var(--r4-text)!important}.sheet{background:#fff!important;border-radius:30px 30px 0 0!important;box-shadow:0 -20px 60px rgba(31,40,61,.18)!important}.sheet-head{background:#fff!important;border-color:var(--r4-line)!important}.sheet .detailgrid>.card:first-child{background:linear-gradient(160deg,#fff5f3,#eef6ff)!important}.sheet .detailgrid>.card:first-child img{filter:drop-shadow(0 18px 24px rgba(35,48,79,.12))!important}.sheet .card,.modal>div{background:#fff!important;border-color:var(--r4-line)!important}.sheet .btn.primary,.modal .btn.primary{background:var(--r4-red)!important;color:#fff!important;border:0!important}
/* Menu */
.mobile-more{background:#fff!important;color:var(--r4-text)!important;border:0!important;border-radius:28px 28px 0 0!important;box-shadow:0 -16px 48px rgba(35,48,79,.15)!important}.mobile-more-head b{color:var(--r4-text)!important}.mobile-more-head button{background:#f4f5f8!important;color:#6d7689!important}.mobile-more>button:not(.mobile-more-head button){background:#f8f9fb!important;color:var(--r4-text)!important;border:1px solid var(--r4-line)!important;border-radius:15px!important}.mobile-more>button span{display:none!important}.mobile-more-backdrop{background:rgba(31,40,61,.18)!important;backdrop-filter:blur(4px)!important}
/* Bottom navigation from reference */
.mobile-nav{display:grid!important;grid-template-columns:repeat(3,1fr)!important;position:fixed!important;left:16px!important;right:16px!important;bottom:max(10px,env(safe-area-inset-bottom))!important;height:76px!important;padding:6px!important;background:rgba(255,255,255,.97)!important;border:1px solid var(--r4-line)!important;border-radius:25px!important;box-shadow:0 14px 42px rgba(35,48,79,.13)!important;backdrop-filter:blur(14px)!important;z-index:60!important}.mnav-item[data-v="global"],.mnav-item[data-v="missing"]{display:none!important}.mnav-item{color:#7d879b!important;border-radius:19px!important;min-height:62px!important;background:transparent!important}.mnav-item.active{background:var(--r4-soft-red)!important;color:var(--r4-red)!important;box-shadow:none!important}.mnav-icon svg{stroke-width:2!important}.mnav-item span:last-child{font-size:10px!important;font-weight:800!important}
/* Buttons */
.btn,button{font-family:inherit!important}.btn{background:#fff!important;color:var(--r4-text)!important;border:1px solid var(--r4-line)!important;border-radius:14px!important;box-shadow:none!important;font-weight:800!important}.btn.primary,.btn.green{background:var(--r4-red)!important;color:#fff!important;border-color:var(--r4-red)!important}.btn:active,.mnav-item:active,.mobile-more button:active{transform:scale(.975)!important}
/* Animations: small, polished, consistent */
.view.active{animation:r4View .30s cubic-bezier(.2,.75,.2,1)!important}@keyframes r4View{from{opacity:0;transform:translateY(10px)}to{opacity:1;transform:none}}.playing-card{animation:r4Hero .45s cubic-bezier(.2,.75,.2,1)}@keyframes r4Hero{from{opacity:.35;transform:scale(.985)}to{opacity:1;transform:scale(1)}}.pk,.game,.journey-card,.journey-panel,.family-card,.metric{animation:r4Card .32s ease both}@keyframes r4Card{from{opacity:0;transform:translateY(6px)}to{opacity:1;transform:none}}.premium-progress i,.journey-progress>i,.journey-route-progress>i{animation:r4Progress .65s ease-out both;transform-origin:left}@keyframes r4Progress{from{transform:scaleX(0)}to{transform:scaleX(1)}}.sheet{animation:r4Sheet .26s cubic-bezier(.2,.75,.2,1)!important}@keyframes r4Sheet{from{transform:translateY(24px);opacity:.5}to{transform:none;opacity:1}}@media(prefers-reduced-motion:reduce){*{animation-duration:.01ms!important;transition-duration:.01ms!important}}
@media(max-width:700px){.wrap{padding:8px 12px calc(100px + env(safe-area-inset-bottom))!important}.v4-appbar{min-height:66px}.v4-ball{width:42px;height:42px}.v4-brand-text b{font-size:22px}.v4-avatar{width:39px;height:39px}#home .playing-card{min-height:405px!important;padding:20px!important;border-radius:27px!important}.playing-name{margin-top:145px!important}.playing-actions .btn{min-height:56px!important}.dexgrid{grid-template-columns:repeat(3,minmax(0,1fr))!important}.sheet{max-height:96dvh!important}.nav23-general-switch{top:4px!important}}
@media(max-width:390px){.dexgrid{grid-template-columns:repeat(2,minmax(0,1fr))!important}.v4-brand-text small{display:none}}
'''
if '/* Living Dex Hub 4.0' not in s:s=s.replace('</style>',css+'\n</style>',1)
js=r'''
function r4PokemonImg(id){return `<img src="assets/pokemon/${id}.png" alt="" onerror="this.style.display='none'">`}
function r4Appbar(){
 let b=document.getElementById('r4Appbar');if(!b){b=document.createElement('header');b.id='r4Appbar';b.className='v4-appbar';b.innerHTML=`<div class="v4-brand"><span class="v4-ball"></span><span class="v4-brand-text"><b>Living Dex <em>Hub</em></b><small>capture · registre · explore</small></span></div><span class="v4-avatar">${r4PokemonImg(25)}</span>`;const w=document.querySelector('.wrap');if(w)w.prepend(b)}
}
function r4Home(){
 const h=document.getElementById('home');if(!h)return;
 // The approved concept is content-first. Remove all explanatory/title chrome from Home.
 h.querySelectorAll('.home-current-head,.home-intro,.home-heading,.hero,.scope-note').forEach(x=>x.remove());
 const card=h.querySelector('.playing-card');if(card){card.querySelectorAll('p').forEach(x=>x.remove());}
}
function r4Menu(){const mh=document.querySelector('.mobile-more-head b');if(mh)mh.textContent='Menu';document.querySelectorAll('.mobile-more>button span').forEach(x=>x.remove())}
function r4Nav(){const g=document.querySelector('.mnav-item[data-v="games"] span:last-child');if(g)g.textContent='Geral';const m=document.querySelector('#mobileMoreBtn span:last-child');if(m)m.textContent='Menu'}
function r4Apply(){r4Appbar();r4Home();r4Menu();r4Nav();document.body.classList.add('reference-v4')}
const r4Go=window.go;window.go=function(){const r=r4Go.apply(this,arguments);setTimeout(r4Apply,0);return r};
const r4HomeRender=window.renderActiveGameHome;if(typeof r4HomeRender==='function')window.renderActiveGameHome=function(){const r=r4HomeRender.apply(this,arguments);setTimeout(r4Apply,0);return r};
setTimeout(r4Apply,0);
if(new URLSearchParams(location.search).has('r4qa'))setTimeout(()=>{
 const ok=!!document.getElementById('r4Appbar')&&document.body.classList.contains('reference-v4')&&!document.querySelector('#home .home-current-head')&&!!document.querySelector('.mobile-nav')&&!!document.querySelector('.playing-card')&&!!document.querySelector('meta[name="living-dex-reference-ui"]');document.documentElement.dataset.r4Qa=ok?'1':'0';
},1100);
'''
s=s.replace('</body>','<script>'+js+'</script>\n</body>',1)
p.write_text(s,encoding='utf-8')
print('Reference UI 4.0 applied')
