from pathlib import Path
p=Path(__file__).resolve().parents[1]/'app/src/main/assets/index.html'
s=p.read_text(encoding='utf-8')
if 'living-dex-dedicated-journey" content="4.2"' not in s:
    s=s.replace('</head>','<meta name="living-dex-dedicated-journey" content="4.2"/>\n</head>',1)
css=r'''
/* Dedicated Journey pages 4.2 — each Home card opens a true page. */
body.ref42-page-open{overflow:hidden!important}.ref42-page{position:fixed;inset:0;z-index:900;background:#f7f8fb;color:#17213c;display:flex;flex-direction:column;animation:ref42PageIn .22s ease both}.ref42-page[hidden]{display:none!important}@keyframes ref42PageIn{from{opacity:0;transform:translateX(14px)}to{opacity:1;transform:none}}
.ref42-head{flex:0 0 auto;display:flex;align-items:center;gap:12px;padding:calc(10px + env(safe-area-inset-top)) 16px 11px;background:rgba(247,248,251,.96);border-bottom:1px solid #edf0f5;backdrop-filter:blur(14px);z-index:5}.ref42-back{width:43px;height:43px;border:0;border-radius:14px;background:#fff;color:#17213c;box-shadow:0 4px 14px rgba(35,48,79,.07);font-size:24px;display:grid;place-items:center}.ref42-headtext{min-width:0}.ref42-headtext h1{margin:0;font-size:24px;line-height:1.05;font-weight:850;letter-spacing:-.045em}.ref42-headtext small{display:block;margin-top:4px;color:#929caf;font-size:9px;font-weight:650}.ref42-headicon{margin-left:auto;width:38px;height:38px;border-radius:13px;display:grid;place-items:center;background:#fff0f0;color:#ff5555}.ref42-headicon svg{width:20px;height:20px}.ref42-content{flex:1 1 auto;min-height:0;overflow:auto;padding:14px 15px calc(24px + env(safe-area-inset-bottom));overscroll-behavior:contain}.ref42-page.map .ref42-content{padding:0;overflow:hidden}.ref42-page.map .ref42-head{position:absolute;left:0;right:0;top:0;background:linear-gradient(180deg,rgba(247,248,251,.96),rgba(247,248,251,.86));border-bottom:0}.ref42-page.map .ref42-mapstage{position:absolute;inset:0;background:#78b8ca}.ref42-page.map .paldea-map{position:absolute!important;inset:0!important;width:100%!important;height:100%!important;min-height:0!important;aspect-ratio:auto!important;border-radius:0!important;border:0!important;box-shadow:none!important}.ref42-page.map .paldea-map-art{object-fit:contain!important;background:#78b8ca!important}.ref42-page.map .map-caption{top:calc(82px + env(safe-area-inset-top))!important}.ref42-page.map .map-full{display:none!important}.ref42-page.map .map-legend{bottom:calc(14px + env(safe-area-inset-bottom))!important}.ref42-page.map .map-next-label{bottom:calc(48px + env(safe-area-inset-bottom))!important}.ref42-map-help{position:absolute;left:14px;right:14px;bottom:calc(10px + env(safe-area-inset-bottom));z-index:12;pointer-events:none}.ref42-map-chip{display:inline-flex;padding:7px 10px;border-radius:999px;background:rgba(255,255,255,.92);box-shadow:0 5px 16px rgba(35,48,79,.12);color:#677287;font-size:9px;font-weight:750}
.ref42-progress-top{display:grid;grid-template-columns:1fr auto;gap:10px;align-items:center;padding:14px 15px;margin-bottom:12px;border-radius:20px;background:#fff;border:1px solid #edf0f5;box-shadow:0 5px 16px rgba(35,48,79,.06)}.ref42-progress-top b{display:block;font-size:17px}.ref42-progress-top small{color:#929caf;font-size:9px}.ref42-count{font-size:20px;font-weight:850;color:#ff5555}.ref42-bar{height:7px;border-radius:99px;background:#eef1f5;overflow:hidden;margin-top:9px}.ref42-bar i{display:block;height:100%;background:#ff5555;border-radius:99px}.ref42-list{display:grid;gap:9px}.ref42-step{display:grid;grid-template-columns:40px 1fr auto;gap:11px;align-items:center;padding:13px 12px;border:1px solid #edf0f5;border-radius:18px;background:#fff;box-shadow:0 4px 14px rgba(35,48,79,.05)}.ref42-step.done{background:#f8fffc;border-color:#d9f1e7}.ref42-step.next{border-color:#ffd1d1;box-shadow:0 6px 18px rgba(255,85,85,.09)}.ref42-check{width:36px;height:36px;border-radius:50%;border:2px solid #dce1e9;background:#fff;color:#9fa8b8;font-size:11px;font-weight:900}.ref42-step.done .ref42-check{background:#22c993;border-color:#22c993;color:#fff}.ref42-step.next .ref42-check{border-color:#ff5555;color:#ff5555}.ref42-step b{display:block;font-size:13px}.ref42-step small{display:block;margin-top:3px;color:#929caf;font-size:9px}.ref42-level{padding:6px 8px;border-radius:999px;background:#f3f5f8;color:#737e92;font-size:9px;font-weight:850}
.ref42-teamhero{padding:16px;margin-bottom:12px;border:1px solid #edf0f5;border-radius:22px;background:linear-gradient(145deg,#fff,#f4f8ff);box-shadow:0 5px 17px rgba(35,48,79,.06)}.ref42-teamhero .eyebrow{font-size:9px;text-transform:uppercase;letter-spacing:.09em;color:#5398ff;font-weight:850}.ref42-teamhero h2{margin:5px 0 4px;font-size:20px}.ref42-teamhero p{margin:0;color:#8f99aa;font-size:10px;line-height:1.45}.ref42-teamgrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.ref42-member{position:relative;padding:14px 12px 12px;border:1px solid #edf0f5;border-radius:21px;background:#fff;box-shadow:0 5px 16px rgba(35,48,79,.06);text-align:left;color:#17213c}.ref42-member img{width:96px;height:96px;display:block;object-fit:contain;margin:0 auto 6px}.ref42-member b{display:block;font-size:14px}.ref42-member small{display:block;color:#929caf;font-size:9px;margin-top:3px}.ref42-rank{display:inline-block;margin-top:8px;padding:5px 7px;border-radius:999px;background:#edf5ff;color:#4f8fe8;font-size:8px;font-weight:850}.ref42-member.best{border-color:#cfe5ff;background:#fafdff}.ref42-member.best .ref42-rank{background:#eafaf4;color:#169d70}.ref42-owned{position:absolute;right:10px;top:10px;width:24px;height:24px;border-radius:50%;display:grid;place-items:center;background:#eafaf4;color:#15996e;font-size:11px;font-weight:900}
/* Home cards stay launchers only. */
.ref41-card{cursor:pointer!important}.ref41-card.route,.ref41-card.team,.ref41-card.map{min-height:160px!important}.ref41-card.route:after,.ref41-card.team:after,.ref41-card.map:after{content:'›'!important}
@media(max-width:390px){.ref42-teamgrid{grid-template-columns:1fr 1fr}.ref42-member img{width:82px;height:82px}.ref42-headtext h1{font-size:22px}}
'''
s=s.replace('</style>',css+'\n</style>',1)
js=r'''
// Dedicated Journey pages 4.2.
const REF42_ICON={route:REF41_ICONS?.route||'',team:REF41_ICONS?.team||'',map:REF41_ICONS?.map||''};
function ref42EnsurePages(){if(document.getElementById('ref42RoutePage'))return;document.body.insertAdjacentHTML('beforeend',`<section id="ref42RoutePage" class="ref42-page route" hidden></section><section id="ref42TeamPage" class="ref42-page team" hidden></section><section id="ref42MapPage" class="ref42-page map" hidden></section>`)}
function ref42HideAll(){document.querySelectorAll('.ref42-page').forEach(p=>p.hidden=true);document.body.classList.remove('ref42-page-open');document.getElementById('ref41Hub')?.remove()}
function ref42Header(title,sub,kind){return `<div class="ref42-head"><button class="ref42-back" onclick="ref42Close()" aria-label="Voltar">‹</button><div class="ref42-headtext"><h1>${title}</h1><small>${sub}</small></div><span class="ref42-headicon">${REF42_ICON[kind]||''}</span></div>`}
function ref42Open(kind){ref42EnsurePages();document.getElementById('ref41Hub')?.remove();document.querySelectorAll('.ref42-page').forEach(p=>p.hidden=true);const page=document.getElementById(kind==='route'?'ref42RoutePage':kind==='team'?'ref42TeamPage':'ref42MapPage');if(!page)return;page.hidden=false;document.body.classList.add('ref42-page-open');if(kind==='route')ref42RenderRoute();else if(kind==='team')ref42RenderTeam();else ref42RenderMap();setTimeout(()=>page.querySelector('.ref42-content')?.scrollTo({top:0,behavior:'auto'}),0)}
function ref42Close(){ref42HideAll();if(typeof go==='function')go('home');setTimeout(()=>{if(typeof ref41Home==='function')ref41Home()},0)}
function ref42RouteStats(){const done=state.journey?.sv?.done||{};const count=Object.values(done).filter(Boolean).length;return {done,count,pct:Math.round(count/18*100),next:typeof svNextIndex==='function'?svNextIndex():1}}
function ref42RenderRoute(){const page=document.getElementById('ref42RoutePage'),d=ref42RouteStats();if(!page)return;page.innerHTML=`${ref42Header('Progressão','Pokémon Scarlet / Violet · ordem por nível','route')}<div class="ref42-content"><div class="ref42-progress-top"><div><b>${d.count} de 18 concluídos</b><small>Toque no círculo de cada objetivo para marcar ou desmarcar.</small><div class="ref42-bar"><i style="width:${d.pct}%"></i></div></div><span class="ref42-count">${d.pct}%</span></div><div class="ref42-list">${SV_ROUTE.map((r,i)=>{const n=i+1,done=!!d.done[n],kind=r[1]==='gym'?'Ginásio':r[1]==='titan'?'Titã':'Team Star';return `<article class="ref42-step ${done?'done':''} ${d.next===n?'next':''}"><button class="ref42-check" onclick="ref42Toggle(${n})">${done?'✓':n}</button><div><b>${r[0]}</b><small>${kind} · ${r[3]}</small></div><span class="ref42-level">Lv.${r[2]}</span></article>`}).join('')}</div></div>`}
function ref42Toggle(n){state.journey=state.journey||{};state.journey.sv=state.journey.sv||{};state.journey.sv.done=state.journey.sv.done||{};state.journey.sv.done[n]=!state.journey.sv.done[n];try{save()}catch(e){}ref42RenderRoute();setTimeout(()=>{if(typeof ref41Home==='function')ref41Home()},0)}
function ref42RenderTeam(){const page=document.getElementById('ref42TeamPage'),d=typeof ref41Data==='function'?ref41Data():null,boss=d?.next?.r,items=d?.next?.items||d?.ids?.map(id=>({id,owned:false,good:false}))||[];if(!page)return;page.innerHTML=`${ref42Header('Time recomendado','Equipe e builds para o próximo objetivo','team')}<div class="ref42-content"><div class="ref42-teamhero"><div class="eyebrow">${boss?'Próximo desafio':'Jornada concluída'}</div><h2>${boss?boss[0]:'Sua equipe de Paldea'}</h2><p>${boss?`Nível recomendado ${boss[2]} · foco ${boss[3]}. A ordem abaixo considera fase, starter, versão e registros da sua coleção.`:'Consulte e ajuste suas builds mesmo após concluir a rota principal.'}</p></div><div class="ref42-teamgrid">${items.map((x,i)=>{const name=typeof svMemberName==='function'?svMemberName(x.id):'#'+x.id,types=typeof svMemberTypes==='function'?svMemberTypes(x.id).join(' / '):'',owned=x.owned||false;return `<button class="ref42-member ${i===0?'best':''}" onclick="openJourneyBuild(${x.id})">${owned?'<span class="ref42-owned">✓</span>':''}${pokemonImageHTML(x.id,'')}<b>${name}</b><small>${types||'Cobertura variada'}</small><span class="ref42-rank">${i===0?'Melhor escolha':x.good?'Boa opção':'Cobertura'}</span></button>`}).join('')}</div></div>`}
function ref42RenderMap(){const page=document.getElementById('ref42MapPage');if(!page)return;page.innerHTML=`${ref42Header('Mapa de Paldea','18 objetivos · posição e nível recomendado','map')}<div class="ref42-content"><div class="ref42-mapstage">${journeyMap()}</div><div class="ref42-map-help"><span class="ref42-map-chip">Toque nos marcadores para ver objetivo e nível</span></div></div>`}
// Replace the 4.1 hub routing. Home cards now launch dedicated pages.
window.ref41Open=function(kind='route'){ref42Open(kind)};
// Android/system back closes the dedicated page first.
const ref42AndroidBack=window.androidHandleBack;
window.androidHandleBack=function(){const open=[...document.querySelectorAll('.ref42-page')].some(p=>!p.hidden);if(open){ref42Close();return true}return typeof ref42AndroidBack==='function'?ref42AndroidBack():false};
ref42EnsurePages();
'''
s=s.replace('</body>','<script>'+js+'</script>\n</body>',1)
p.write_text(s,encoding='utf-8')
print('Dedicated Journey pages 4.2 applied')