from pathlib import Path
p=Path(__file__).resolve().parents[1]/'app'/'src'/'main'/'assets'/'index.html'
s=p.read_text(encoding='utf-8')
if 'living-dex-reference-structure" content="4.1"' not in s:
    s=s.replace('</head>','<meta name="living-dex-reference-structure" content="4.1"/>\n</head>',1)
css=r'''
/* Reference Structure 4.1 — approved concept is now structural, not a skin. */
#home .home232-journey,#home .home-journey-summary{display:none!important}
.ref41-journey{margin:26px 0 8px}.ref41-title{display:flex;align-items:center;gap:10px;margin-bottom:13px}.ref41-title-icon{width:35px;height:35px;border-radius:12px;background:#fff0f0;color:#ff5555;display:grid;place-items:center;box-shadow:0 4px 14px rgba(35,48,79,.07)}.ref41-title-icon svg{width:19px;height:19px}.ref41-title h2{margin:0;color:#17213c;font-size:23px;letter-spacing:-.04em}.ref41-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.ref41-card{position:relative;min-height:176px;padding:17px;border:1px solid #edf0f5;border-radius:23px;background:#fff;box-shadow:0 7px 22px rgba(35,48,79,.075);text-align:left;color:#17213c;overflow:hidden;cursor:pointer;transition:transform .18s ease,box-shadow .18s ease}.ref41-card:active{transform:scale(.975)}.ref41-card:after{content:'›';position:absolute;right:15px;top:17px;font-size:25px;line-height:1;color:#c6ccd8}.ref41-icon{width:45px;height:45px;border-radius:15px;display:grid;place-items:center;margin-bottom:18px}.ref41-icon svg{width:23px;height:23px}.ref41-card.route .ref41-icon{background:#fff0f0;color:#ff5555}.ref41-card.team .ref41-icon{background:#edf5ff;color:#5398ff}.ref41-card.map .ref41-icon{background:#eafaf4;color:#20b985}.ref41-card .label{display:block;font-size:10px;text-transform:uppercase;letter-spacing:.1em;color:#9ba4b6;font-weight:850}.ref41-card b{display:block;margin-top:6px;font-size:16px;line-height:1.2;letter-spacing:-.02em}.ref41-card small{display:block;margin-top:7px;color:#8b95a8;font-size:10px;line-height:1.45}.ref41-progress{height:5px;border-radius:99px;background:#eef1f5;margin-top:13px;overflow:hidden}.ref41-progress i{display:block;height:100%;border-radius:99px;background:#ff5555}.ref41-pokes{display:flex;align-items:center;margin-top:12px}.ref41-pokes img{width:37px;height:37px;object-fit:contain;background:#f7f8fb;border:2px solid #fff;border-radius:50%;margin-left:-7px;box-shadow:0 3px 9px rgba(35,48,79,.08)}.ref41-pokes img:first-child{margin-left:0}.ref41-mapmini{position:absolute;left:0;right:0;bottom:0;height:70px;background:url('assets/maps/paldea-route.svg') center/cover no-repeat;opacity:.23;mask-image:linear-gradient(transparent,#000);-webkit-mask-image:linear-gradient(transparent,#000)}
/* Journey hub */
.ref41-hub{padding:2px 0 16px}.ref41-hubhead{display:flex;align-items:center;gap:11px;margin:6px 0 18px}.ref41-back{width:42px;height:42px;border:0;border-radius:14px;background:#fff;box-shadow:0 4px 15px rgba(35,48,79,.07);color:#17213c;font-size:22px}.ref41-hubhead h1{margin:0;font-size:27px;letter-spacing:-.045em}.ref41-hubhead small{color:#929caf}.ref41-tabs{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;padding:5px;background:#fff;border:1px solid #edf0f5;border-radius:18px;box-shadow:0 5px 18px rgba(35,48,79,.06);margin-bottom:16px}.ref41-tabs button{min-height:45px;border:0;border-radius:14px;background:transparent;color:#8b95a8;font-weight:800}.ref41-tabs button.active{background:#fff0f0;color:#ff5555}.ref41-pane{animation:r4In .24s ease both}.ref41-route-list{display:grid;gap:9px}.ref41-step{display:grid;grid-template-columns:38px 1fr auto;gap:11px;align-items:center;padding:13px;background:#fff;border:1px solid #edf0f5;border-radius:18px;box-shadow:0 4px 15px rgba(35,48,79,.055)}.ref41-step.done{background:#f8fffc;border-color:#daf2e8}.ref41-step.next{border-color:#ffd3d3;box-shadow:0 6px 18px rgba(255,85,85,.10)}.ref41-check{width:34px;height:34px;border-radius:50%;border:2px solid #dce1e9;background:#fff;color:#a1aabc;font-weight:900}.ref41-step.done .ref41-check{background:#22c993;border-color:#22c993;color:#fff}.ref41-step.next .ref41-check{border-color:#ff5555;color:#ff5555}.ref41-step b{font-size:13px}.ref41-step small{display:block;color:#929caf;font-size:9px;margin-top:3px}.ref41-level{padding:6px 8px;border-radius:999px;background:#f4f6f9;color:#737e92;font-size:9px;font-weight:850}.ref41-teamgrid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.ref41-member{padding:14px;background:#fff;border:1px solid #edf0f5;border-radius:20px;box-shadow:0 5px 17px rgba(35,48,79,.06);cursor:pointer}.ref41-member img{width:88px;height:88px;object-fit:contain;display:block;margin:auto}.ref41-member b{display:block;font-size:14px}.ref41-member small{color:#929caf;font-size:9px}.ref41-member .rank{display:inline-block;margin-top:7px;padding:5px 7px;border-radius:999px;background:#edf5ff;color:#4d8de7;font-size:8px;font-weight:850}.ref41-map-shell{background:#fff;border:1px solid #edf0f5;border-radius:24px;padding:10px;box-shadow:0 6px 20px rgba(35,48,79,.07)}.ref41-map-shell .paldea-map{border-radius:18px!important;box-shadow:none!important;border:0!important}.ref41-note{padding:12px 14px;margin-bottom:12px;border-radius:16px;background:#fff8ee;color:#8c6b3e;font-size:10px;line-height:1.5}
@media(max-width:680px){.ref41-grid{grid-template-columns:1fr}.ref41-card{min-height:144px}.ref41-teamgrid{grid-template-columns:1fr 1fr}.ref41-hubhead h1{font-size:24px}}
'''
s=s.replace('</style>',css+'\n</style>',1)
js=r'''
// Reference Structure 4.1 — Journey is a 3-door hub matching the approved reference.
const REF41_ICONS={journey:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M5 20V9l7-5 7 5v11"/><path d="M9 20v-6h6v6"/></svg>',route:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="6" cy="18" r="2"/><circle cx="18" cy="6" r="2"/><path d="M7.5 16.5c2-5 7-3 9-8"/></svg>',team:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="9" cy="8" r="3"/><circle cx="17" cy="10" r="2"/><path d="M3 20c.5-4 2.5-6 6-6s5.5 2 6 6M15 15c3 0 5 1.5 6 4"/></svg>',map:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M3 6l6-3 6 3 6-3v15l-6 3-6-3-6 3z"/><path d="M9 3v15M15 6v15"/></svg>'};
function ref41Data(){const done=state.journey?.sv?.done||{};const count=Object.values(done).filter(Boolean).length;const next=typeof svSmartPrepData==='function'?svSmartPrepData():null;const ids=typeof svRecommendedTeamIds==='function'?svRecommendedTeamIds():[];return {done,count,next,ids}}
function ref41Home(){const home=document.getElementById('home');if(!home)return;home.querySelectorAll('.ref41-journey').forEach(x=>x.remove());if(state.activeGameId!=='sv')return;const shell=home.querySelector('.home-current-shell');if(!shell)return;const d=ref41Data(),next=d.next?.r?.[0]||'Rota concluída',lv=d.next?.r?.[2],pct=Math.round(d.count/18*100);const poke=d.ids.slice(0,3).map(id=>pokemonImageHTML(id,'')).join('');shell.insertAdjacentHTML('afterend',`<section class="ref41-journey"><div class="ref41-title"><span class="ref41-title-icon">${REF41_ICONS.journey}</span><h2>Jornada</h2></div><div class="ref41-grid"><button class="ref41-card route" onclick="ref41Open('route')"><span class="ref41-icon">${REF41_ICONS.route}</span><span class="label">Próximo objetivo</span><b>${next}</b><small>${lv?`Siga a progressão recomendada · Lv.${lv}`:'Os 18 objetivos principais foram concluídos.'}</small><div class="ref41-progress"><i style="width:${pct}%"></i></div></button><button class="ref41-card team" onclick="ref41Open('team')"><span class="ref41-icon">${REF41_ICONS.team}</span><span class="label">Time recomendado</span><b>Equipe para sua fase</b><small>Pokémon, vantagem de tipo e build sugerida.</small><div class="ref41-pokes">${poke}</div></button><button class="ref41-card map" onclick="ref41Open('map')"><span class="ref41-icon">${REF41_ICONS.map}</span><span class="label">Mapa</span><b>Rota de Paldea</b><small>Veja onde fica cada objetivo e o nível recomendado.</small><span class="ref41-mapmini"></span></button></div></section>`)}
function ref41Close(){document.getElementById('ref41Hub')?.remove();document.body.classList.remove('ref41-open');go('home')}
function ref41Open(tab='route'){document.getElementById('ref41Hub')?.remove();document.body.classList.add('ref41-open');document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));const main=document.querySelector('.wrap')||document.body;main.insertAdjacentHTML('beforeend',`<section id="ref41Hub" class="ref41-hub"><div class="ref41-hubhead"><button class="ref41-back" onclick="ref41Close()">‹</button><div><h1>Jornada</h1><small>Pokémon Scarlet / Violet</small></div></div><div class="ref41-tabs"><button data-t="route" onclick="ref41Tab('route')">Progressão</button><button data-t="team" onclick="ref41Tab('team')">Time</button><button data-t="map" onclick="ref41Tab('map')">Mapa</button></div><div id="ref41Pane" class="ref41-pane"></div></section>`);ref41Tab(tab);window.scrollTo({top:0,behavior:'auto'})}
function ref41Tab(tab){document.querySelectorAll('#ref41Hub .ref41-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.t===tab));const pane=document.getElementById('ref41Pane');if(!pane)return;pane.innerHTML=tab==='route'?ref41Route():tab==='team'?ref41Team():ref41Map()}
function ref41Toggle(n){state.journey=state.journey||{};state.journey.sv=state.journey.sv||{};state.journey.sv.done=state.journey.sv.done||{};state.journey.sv.done[n]=!state.journey.sv.done[n];try{save()}catch(e){try{localStorage.setItem('livingDexHubState',JSON.stringify(state))}catch(_){}}ref41Tab('route')}
function ref41Route(){const done=state.journey?.sv?.done||{};const next=typeof svNextIndex==='function'?svNextIndex():1;return `<div class="ref41-note">Marque cada etapa conforme concluir. A ordem abaixo segue a progressão por nível recomendada para evitar saltos bruscos de dificuldade.</div><div class="ref41-route-list">${SV_ROUTE.map((r,i)=>{const n=i+1,d=!!done[n];return `<div class="ref41-step ${d?'done':''} ${next===n?'next':''}"><button class="ref41-check" onclick="ref41Toggle(${n})">${d?'✓':n}</button><div><b>${r[0]}</b><small>${r[1]==='gym'?'Ginásio':r[1]==='titan'?'Titã':'Team Star'} · foco ${r[3]}</small></div><span class="ref41-level">Lv.${r[2]}</span></div>`}).join('')}</div>`}
function ref41Team(){const d=ref41Data(),boss=d.next?.r,items=d.next?.items||d.ids.map(id=>({id,owned:false,good:false}));return `<div class="ref41-note">${boss?`Preparação para <b>${boss[0]}</b> · Lv.${boss[2]} · ${boss[3]}. Toque em um Pokémon para abrir a build completa.`:'Rota principal concluída. Você ainda pode consultar suas builds.'}</div><div class="ref41-teamgrid">${items.map((x,i)=>`<div class="ref41-member" onclick="openJourneyBuild(${x.id})">${pokemonImageHTML(x.id,'')}<b>${typeof svMemberName==='function'?svMemberName(x.id):'#'+x.id}</b><small>${typeof svMemberTypes==='function'?svMemberTypes(x.id).join(' / '):''}</small><span class="rank">${i===0?'Melhor escolha':x.good?'Boa opção':'Cobertura'}</span></div>`).join('')}</div>`}
function ref41Map(){return `<div class="ref41-note">Mapa de Paldea com os 18 objetivos posicionados e numerados na mesma ordem da progressão. Toque nos marcadores para identificar objetivo e nível.</div><div class="ref41-map-shell">${journeyMap()}</div>`}
const ref41BaseRender=window.renderActiveGameHome;if(typeof ref41BaseRender==='function'){window.renderActiveGameHome=function(){const r=ref41BaseRender.apply(this,arguments);setTimeout(ref41Home,0);return r}}
setTimeout(()=>{if(document.getElementById('home')?.classList.contains('active'))ref41Home()},80);
'''
s=s.replace('</body>','<script>'+js+'</script>\n</body>',1)
p.write_text(s,encoding='utf-8')
print('Reference Structure 4.1 applied')