from pathlib import Path
p=Path(__file__).resolve().parents[1]/'app/src/main/assets/index.html'
s=p.read_text(encoding='utf-8')
if 'living-dex-paldea-map" content="4.3"' not in s:s=s.replace('</head>','<meta name="living-dex-paldea-map" content="4.3"/>\n</head>',1)
css=r'''
/* Paldea Map 4.3 — dedicated, navigable and geographically aligned. */
.ref43-mapviewport{position:absolute;inset:0;overflow:hidden;background:#72b2c4;touch-action:none}.ref43-mapcanvas{position:absolute;inset:0;transform-origin:50% 50%;will-change:transform;transition:transform .12s ease}.ref43-mapcanvas.dragging{transition:none}.ref43-controls{position:absolute;right:12px;top:calc(82px + env(safe-area-inset-top));z-index:30;display:grid;gap:7px}.ref43-controls button{width:42px;height:42px;border:0;border-radius:14px;background:rgba(255,255,255,.94);color:#17213c;font-size:19px;font-weight:850;box-shadow:0 5px 16px rgba(35,48,79,.13)}.ref43-detail{position:absolute;left:12px;right:12px;bottom:calc(12px + env(safe-area-inset-bottom));z-index:35;padding:14px 15px;border:1px solid rgba(237,240,245,.9);border-radius:21px;background:rgba(255,255,255,.96);box-shadow:0 10px 30px rgba(35,48,79,.16);backdrop-filter:blur(14px);transform:translateY(calc(100% + 30px));opacity:0;transition:.2s ease}.ref43-detail.open{transform:none;opacity:1}.ref43-detailtop{display:grid;grid-template-columns:auto 1fr auto;gap:10px;align-items:center}.ref43-num{width:38px;height:38px;border-radius:13px;background:#fff0f0;color:#ff5555;display:grid;place-items:center;font-weight:900}.ref43-detail b{display:block;font-size:14px}.ref43-detail small{display:block;margin-top:3px;color:#8f99aa;font-size:9px}.ref43-close{width:32px;height:32px;border:0;border-radius:11px;background:#f3f5f8;color:#7a8497}.ref43-actions{display:flex;gap:7px;margin-top:11px}.ref43-actions button{flex:1;min-height:40px;border:0;border-radius:13px;font-weight:800}.ref43-primary{background:#ff5555;color:#fff}.ref43-secondary{background:#f2f5f8;color:#59667c}.geo-node{width:31px!important;height:31px!important;font-size:8px!important;border:2px solid rgba(255,255,255,.9)!important;box-shadow:0 5px 14px rgba(34,54,76,.27)!important}.geo-node.gym{background:#4d8fe9!important}.geo-node.titan{background:#e29d45!important}.geo-node.star{background:#e05b79!important}.geo-node.next{width:39px!important;height:39px!important;border-color:#fff!important;box-shadow:0 0 0 6px rgba(255,85,85,.22),0 7px 20px rgba(35,48,79,.3)!important;background:#ff5555!important}.geo-node.done{opacity:.55!important;filter:saturate(.6)}.route-polyline polyline{stroke:rgba(255,255,255,.8)!important;stroke-width:2.2!important;stroke-dasharray:4 5!important}.map-caption{background:rgba(255,255,255,.9)!important;color:#526076!important;border:1px solid rgba(237,240,245,.9)!important;box-shadow:0 4px 14px rgba(35,48,79,.1)!important}.map-legend{display:none!important}.map-next-label{display:none!important}
/* Remove the old dark build modal visually. */
.build-sheet{background:rgba(37,48,70,.24)!important;backdrop-filter:blur(10px)!important}.build-card{background:#f7f8fb!important;color:#17213c!important;border:0!important;box-shadow:0 -18px 55px rgba(35,48,79,.18)!important}.build-head h3,.build-card h4,.build-meta b,.move b{color:#17213c!important}.build-head p,.research-note{color:#8f99aa!important}.build-meta div,.move{background:#fff!important;border:1px solid #edf0f5!important;box-shadow:0 3px 11px rgba(35,48,79,.045)!important}.build-meta small,.move small{color:#98a1b1!important}.build-note{background:#edf5ff!important;border:1px solid #dfeafb!important;color:#58687f!important}.research-note a{color:#4d8fe9!important}.build-card .btn{background:#fff!important;color:#687387!important;border:1px solid #e8ebf0!important}
'''
s=s.replace('</style>',css+'\n</style>',1)
js=r'''
// Paldea 4.3: positions aligned to the redrawn map and level route references.
const REF43_POS=[[28,77],[71,67],[66,69],[23,53],[19,47],[77,54],[76,62],[78,42],[25,46],[76,33],[38,37],[52,18],[29,45],[24,72],[45,12],[80,17],[30,18],[83,27]];
try{SV_ROUTE_POS.splice(0,SV_ROUTE_POS.length,...REF43_POS)}catch(e){}
let ref43Zoom=1,ref43X=0,ref43Y=0,ref43Pointers=new Map(),ref43LastDist=0;
function ref43DoneArray(){const raw=state.journey?.sv?.done||[];if(Array.isArray(raw))return raw.map(Number).filter(n=>n>=1&&n<=18);return Object.entries(raw).filter(([k,v])=>v).map(([k])=>Number(k)).filter(n=>n>=1&&n<=18)}
function ref43SetDone(n,value){const set=new Set(ref43DoneArray());value?set.add(n):set.delete(n);state.journey=state.journey||{};state.journey.sv=state.journey.sv||{};state.journey.sv.done=[...set].sort((a,b)=>a-b);try{save()}catch(e){}}
// Repair any v4.1/v4.2 object-shaped progress from earlier builds.
if(state.journey?.sv?.done && !Array.isArray(state.journey.sv.done)){state.journey.sv.done=ref43DoneArray();try{save()}catch(e){}}
function ref43Apply(){const c=document.getElementById('ref43Canvas');if(c)c.style.transform=`translate(${ref43X}px,${ref43Y}px) scale(${ref43Zoom})`}
function ref43ZoomBy(d){ref43Zoom=Math.max(1,Math.min(3.2,ref43Zoom+d));if(ref43Zoom===1){ref43X=0;ref43Y=0}ref43Apply()}
function ref43Reset(){ref43Zoom=1;ref43X=0;ref43Y=0;ref43Apply()}
function ref43Point(n){const r=SV_ROUTE[n-1],d=document.getElementById('ref43Detail');if(!r||!d)return;const done=ref43DoneArray().includes(n),kind=r[1]==='gym'?'Ginásio':r[1]==='titan'?'Titã':'Team Star';d.innerHTML=`<div class="ref43-detailtop"><span class="ref43-num">${n}</span><div><b>${r[0]}</b><small>${kind} · Lv.${r[2]} · foco ${r[3]}</small></div><button class="ref43-close" onclick="ref43ClosePoint()">×</button></div><div class="ref43-actions"><button class="ref43-primary" onclick="ref43TogglePoint(${n})">${done?'Desmarcar concluído':'Marcar concluído'}</button><button class="ref43-secondary" onclick="ref42Open('team')">Ver time</button></div>`;d.classList.add('open')}
function ref43ClosePoint(){document.getElementById('ref43Detail')?.classList.remove('open')}
function ref43TogglePoint(n){ref43SetDone(n,!ref43DoneArray().includes(n));ref42RenderMap();setTimeout(()=>ref43Point(n),30);if(typeof ref41Home==='function')setTimeout(ref41Home,0)}
function ref43MapHtml(){const next=typeof svNextIndex==='function'?svNextIndex():0,done=new Set(ref43DoneArray());return `<div id="ref43Viewport" class="ref43-mapviewport"><div id="ref43Canvas" class="ref43-mapcanvas"><div class="paldea-map"><img class="paldea-map-art" src="assets/maps/paldea-route.svg" alt="Mapa de Paldea" draggable="false"><svg class="route-polyline" viewBox="0 0 100 100" preserveAspectRatio="none"><polyline points="${SV_ROUTE_POS.map(p=>p.join(',')).join(' ')}"></polyline></svg><div class="map-caption">Paldea · rota por nível</div>${SV_ROUTE.map((r,i)=>{const p=SV_ROUTE_POS[i],n=i+1,cls=`${r[1]} ${done.has(n)?'done':''} ${next===n?'next':''}`;return `<button class="geo-node ${cls}" style="left:${p[0]}%;top:${p[1]}%" aria-label="${n}. ${r[0]} nível ${r[2]}" onclick="ref43Point(${n})">${n}</button>`}).join('')}</div></div><div class="ref43-controls"><button onclick="ref43ZoomBy(.35)" aria-label="Aumentar zoom">+</button><button onclick="ref43ZoomBy(-.35)" aria-label="Diminuir zoom">−</button><button onclick="ref43Reset()" aria-label="Restaurar mapa">⌂</button></div><div id="ref43Detail" class="ref43-detail"></div></div>`}
const ref43OldMap=window.ref42RenderMap;window.ref42RenderMap=function(){const page=document.getElementById('ref42MapPage');if(!page)return;ref43Zoom=1;ref43X=0;ref43Y=0;page.innerHTML=`${ref42Header('Mapa de Paldea','18 objetivos · posição e nível recomendado','map')}<div class="ref42-content">${ref43MapHtml()}</div>`;setTimeout(ref43Bind,0)};
function ref43Bind(){const v=document.getElementById('ref43Viewport'),c=document.getElementById('ref43Canvas');if(!v||!c)return;v.onpointerdown=e=>{if(e.target.closest('.geo-node,.ref43-controls,.ref43-detail'))return;v.setPointerCapture?.(e.pointerId);ref43Pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});c.classList.add('dragging')};v.onpointermove=e=>{if(!ref43Pointers.has(e.pointerId))return;const prev=ref43Pointers.get(e.pointerId);ref43Pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(ref43Pointers.size===1&&ref43Zoom>1){ref43X+=e.clientX-prev.x;ref43Y+=e.clientY-prev.y;ref43Apply()}else if(ref43Pointers.size===2){const a=[...ref43Pointers.values()],dist=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);if(ref43LastDist){ref43Zoom=Math.max(1,Math.min(3.2,ref43Zoom+(dist-ref43LastDist)/180));ref43Apply()}ref43LastDist=dist}};const end=e=>{ref43Pointers.delete(e.pointerId);if(ref43Pointers.size<2)ref43LastDist=0;if(!ref43Pointers.size)c.classList.remove('dragging')};v.onpointerup=end;v.onpointercancel=end;v.onwheel=e=>{e.preventDefault();ref43ZoomBy(e.deltaY<0?.2:-.2)}}
// Ensure route toggles always use the canonical array model.
window.ref42Toggle=function(n){ref43SetDone(n,!ref43DoneArray().includes(n));ref42RenderRoute();if(typeof ref41Home==='function')setTimeout(ref41Home,0)};
'''
s=s.replace('</body>','<script>'+js+'</script>\n</body>',1)
p.write_text(s,encoding='utf-8')
print('Paldea map interaction 4.3 applied')