from pathlib import Path
p=Path(__file__).resolve().parents[1]/'app'/'src'/'main'/'assets'/'index.html'
s=p.read_text(encoding='utf-8')
if 'living-dex-audio" content="2.2"' not in s:
    s=s.replace('</head>','<meta name="living-dex-audio" content="2.2"/>\n</head>',1)
css=r'''
/* Audio 2.2 — original Living Dex Hub ambient theme + subtle SFX */
.audio-settings{margin-top:14px;padding:16px;border-radius:20px;border:1px solid rgba(114,213,255,.14);background:linear-gradient(150deg,rgba(79,181,255,.055),rgba(102,224,173,.035));box-shadow:0 14px 36px rgba(0,0,0,.12)}
.audio-settings .audio-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;margin-bottom:13px}.audio-settings .eyebrow{font-size:8px;letter-spacing:.14em;text-transform:uppercase;color:#72d5ff;font-weight:900}.audio-settings h3{margin:4px 0;font-size:16px}.audio-settings p{margin:0;color:#8fa5bc;font-size:9px;line-height:1.5}.audio-grid{display:grid;grid-template-columns:1fr 1fr;gap:9px}.audio-toggle{display:flex;justify-content:space-between;gap:10px;align-items:center;padding:12px;border-radius:15px;border:1px solid rgba(148,180,215,.11);background:rgba(255,255,255,.025)}.audio-toggle b{font-size:10px}.audio-toggle small{display:block;color:#8096ac;font-size:7px;margin-top:2px}.audio-switch{min-width:48px;height:28px;border-radius:999px;border:1px solid rgba(148,180,215,.16);background:#102033;position:relative;cursor:pointer}.audio-switch:after{content:"";position:absolute;width:20px;height:20px;border-radius:50%;left:4px;top:3px;background:#8096ac;transition:.2s}.audio-switch.on{background:rgba(102,224,173,.16);border-color:rgba(102,224,173,.32)}.audio-switch.on:after{left:23px;background:#66e0ad;box-shadow:0 0 12px rgba(102,224,173,.45)}.audio-volume{margin-top:9px;padding:12px;border-radius:15px;border:1px solid rgba(148,180,215,.11);background:rgba(255,255,255,.025)}.audio-volume .row{display:flex;justify-content:space-between;align-items:center;margin-bottom:8px}.audio-volume b{font-size:10px}.audio-volume span{font-size:8px;color:#9cb0c4}.audio-volume input{width:100%;accent-color:#66e0ad}.audio-note{margin-top:9px;font-size:7.5px;line-height:1.5;color:#71869b}.audio-quick{position:fixed;right:14px;top:calc(12px + env(safe-area-inset-top));z-index:7000;width:40px;height:40px;border-radius:14px;border:1px solid rgba(148,180,215,.14);background:rgba(8,20,35,.82);backdrop-filter:blur(16px);color:#d8efff;display:grid;place-items:center;font-size:17px;box-shadow:0 10px 28px rgba(0,0,0,.24)}.audio-quick.muted{opacity:.55}
@media(max-width:520px){.audio-grid{grid-template-columns:1fr}.audio-quick{top:calc(8px + env(safe-area-inset-top));right:8px}}
'''
if '/* Audio 2.2' not in s:s=s.replace('</style>',css+'\n</style>',1)
js=r'''
// Audio 2.2 — original ambient theme; no Nintendo/Pokemon music samples are used.
const LDH_AUDIO_KEY='ldh_audio_v22';
let ldhAudioPrefs=(()=>{try{return Object.assign({music:true,sfx:true,volume:.28},JSON.parse(localStorage.getItem(LDH_AUDIO_KEY)||'{}'))}catch(e){return {music:true,sfx:true,volume:.28}}})();
let ldhCtx=null,ldhMusicGain=null,ldhSfxGain=null,ldhLoopTimer=null,ldhStep=0,ldhStarted=false;
const LDH_NOTE={C4:261.63,D4:293.66,E4:329.63,F4:349.23,G4:392.00,A4:440.00,B4:493.88,C5:523.25,D5:587.33,E5:659.25,G5:783.99,A5:880.00};
const LDH_MELODY=['E5','G5','A5','G5','E5','D5','C5','D5','E5','G5','E5','D5','C5','D5','E5','G5'];
const LDH_BASS=['C4','C4','A4','A4','F4','F4','G4','G4','C4','C4','A4','A4','F4','G4','C4','G4'];
function ldhPersistAudio(){try{localStorage.setItem(LDH_AUDIO_KEY,JSON.stringify(ldhAudioPrefs))}catch(e){}ldhRenderAudioUI()}
function ldhEnsureAudio(){if(ldhCtx)return ldhCtx;const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return null;ldhCtx=new AC();const master=ldhCtx.createGain();master.gain.value=.75;master.connect(ldhCtx.destination);ldhMusicGain=ldhCtx.createGain();ldhMusicGain.gain.value=ldhAudioPrefs.music?ldhAudioPrefs.volume:0;ldhMusicGain.connect(master);ldhSfxGain=ldhCtx.createGain();ldhSfxGain.gain.value=ldhAudioPrefs.sfx?Math.min(.5,ldhAudioPrefs.volume*1.25):0;ldhSfxGain.connect(master);return ldhCtx}
function ldhTone(freq,start,dur,gain=.03,type='sine',dest=ldhMusicGain){if(!ldhCtx||!dest)return;const o=ldhCtx.createOscillator(),g=ldhCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(0,start);g.gain.linearRampToValueAtTime(gain,start+.035);g.gain.exponentialRampToValueAtTime(.0001,start+dur);o.connect(g);g.connect(dest);o.start(start);o.stop(start+dur+.03)}
function ldhScheduleStep(){if(!ldhCtx||!ldhAudioPrefs.music)return;const t=ldhCtx.currentTime+.03;const m=LDH_NOTE[LDH_MELODY[ldhStep%LDH_MELODY.length]],b=LDH_NOTE[LDH_BASS[ldhStep%LDH_BASS.length]];ldhTone(m,t,.62,.018,'triangle');ldhTone(b/2,t,.78,.012,'sine');if(ldhStep%4===0)ldhTone(b,t,.9,.007,'sine');ldhStep=(ldhStep+1)%LDH_MELODY.length}
function ldhStartLoop(){if(!ldhAudioPrefs.music)return;ldhEnsureAudio();if(!ldhCtx)return;if(ldhCtx.state==='suspended')ldhCtx.resume();if(ldhLoopTimer)return;ldhScheduleStep();ldhLoopTimer=setInterval(ldhScheduleStep,720)}
function ldhStopLoop(){if(ldhLoopTimer){clearInterval(ldhLoopTimer);ldhLoopTimer=null}if(ldhMusicGain&&ldhCtx)ldhMusicGain.gain.setTargetAtTime(0,ldhCtx.currentTime,.08)}
function ldhApplyAudio(){ldhEnsureAudio();if(ldhMusicGain&&ldhCtx)ldhMusicGain.gain.setTargetAtTime(ldhAudioPrefs.music?ldhAudioPrefs.volume:0,ldhCtx.currentTime,.08);if(ldhSfxGain&&ldhCtx)ldhSfxGain.gain.setTargetAtTime(ldhAudioPrefs.sfx?Math.min(.5,ldhAudioPrefs.volume*1.25):0,ldhCtx.currentTime,.05);if(ldhAudioPrefs.music)ldhStartLoop();else ldhStopLoop();ldhPersistAudio()}
function ldhSfx(kind='tap'){if(!ldhAudioPrefs.sfx)return;ldhEnsureAudio();if(!ldhCtx)return;if(ldhCtx.state==='suspended')ldhCtx.resume();const t=ldhCtx.currentTime+.005;if(kind==='capture'){ldhTone(659,t,.11,.045,'sine',ldhSfxGain);ldhTone(880,t+.08,.16,.035,'triangle',ldhSfxGain)}else if(kind==='back'){ldhTone(330,t,.10,.026,'sine',ldhSfxGain);ldhTone(262,t+.055,.12,.022,'triangle',ldhSfxGain)}else if(kind==='open'){ldhTone(392,t,.08,.022,'sine',ldhSfxGain);ldhTone(523,t+.045,.11,.025,'triangle',ldhSfxGain)}else{ldhTone(520,t,.055,.018,'sine',ldhSfxGain)}}
function ldhToggleMusic(){ldhAudioPrefs.music=!ldhAudioPrefs.music;ldhApplyAudio();ldhSfx(ldhAudioPrefs.music?'open':'back')}
function ldhToggleSfx(){ldhAudioPrefs.sfx=!ldhAudioPrefs.sfx;ldhApplyAudio();if(ldhAudioPrefs.sfx)ldhSfx('capture')}
function ldhSetVolume(v){ldhAudioPrefs.volume=Math.max(0,Math.min(.6,Number(v)));ldhApplyAudio()}
function ldhAudioPanelHTML(){return `<div class="audio-settings" id="ldhAudioSettings"><div class="audio-head"><div><div class="eyebrow">Som</div><h3>Ambiente do Living Dex Hub</h3><p>Trilha ambiente original e efeitos leves para navegação, registros e Jornada.</p></div></div><div class="audio-grid"><div class="audio-toggle"><div><b>Música</b><small>Trilha ambiente em loop</small></div><button type="button" class="audio-switch ${ldhAudioPrefs.music?'on':''}" aria-label="Alternar música" onclick="ldhToggleMusic()"></button></div><div class="audio-toggle"><div><b>Efeitos</b><small>Toques e confirmações</small></div><button type="button" class="audio-switch ${ldhAudioPrefs.sfx?'on':''}" aria-label="Alternar efeitos" onclick="ldhToggleSfx()"></button></div></div><div class="audio-volume"><div class="row"><b>Volume</b><span>${Math.round(ldhAudioPrefs.volume/0.6*100)}%</span></div><input type="range" min="0" max="0.6" step="0.02" value="${ldhAudioPrefs.volume}" oninput="ldhSetVolume(this.value)"></div><div class="audio-note">A música começa após sua primeira interação com o app, respeitando as regras de áudio do Android/WebView. Não utiliza áudio ou melodias da Nintendo.</div></div>`}
function ldhRenderAudioUI(){const panel=document.getElementById('ldhAudioSettings');if(panel)panel.outerHTML=ldhAudioPanelHTML();const q=document.getElementById('ldhAudioQuick');if(q){q.classList.toggle('muted',!ldhAudioPrefs.music&&!ldhAudioPrefs.sfx);q.textContent=ldhAudioPrefs.music?'♪':(ldhAudioPrefs.sfx?'◌':'×')}}
function ldhInjectSettings(){const settings=document.getElementById('settings');if(!settings||document.getElementById('ldhAudioSettings'))return;settings.insertAdjacentHTML('beforeend',ldhAudioPanelHTML())}
function ldhQuickButton(){if(document.getElementById('ldhAudioQuick'))return;const b=document.createElement('button');b.id='ldhAudioQuick';b.className='audio-quick';b.type='button';b.title='Som';b.setAttribute('aria-label','Configurações de som');b.onclick=()=>{ldhSfx('open');if(typeof go==='function')go('settings');setTimeout(ldhInjectSettings,40)};document.body.appendChild(b);ldhRenderAudioUI()}
function ldhFirstGesture(){if(ldhStarted)return;ldhStarted=true;ldhEnsureAudio();if(ldhCtx?.state==='suspended')ldhCtx.resume();if(ldhAudioPrefs.music)ldhStartLoop()}
document.addEventListener('pointerdown',ldhFirstGesture,{once:true,capture:true});
document.addEventListener('click',e=>{const el=e.target?.closest?.('button,.mnav-item,.game,.pk');if(!el)return;if(el.classList.contains('quick-catch'))ldhSfx(el.classList.contains('is-owned')?'back':'capture');else if(/voltar|fechar|remover/i.test((el.textContent||'')))ldhSfx('back');else ldhSfx('tap')},true);
document.addEventListener('visibilitychange',()=>{if(document.hidden)ldhStopLoop();else if(ldhAudioPrefs.music&&ldhStarted)ldhStartLoop()});
const ldhOldGo=window.go;if(typeof ldhOldGo==='function'){window.go=function(v){const r=ldhOldGo.apply(this,arguments);setTimeout(()=>{ldhInjectSettings();ldhRenderAudioUI()},0);return r}}
setTimeout(()=>{ldhInjectSettings();ldhQuickButton()},0);
'''
s=s.replace('</body>','<script>'+js+'</script>\n</body>',1)
p.write_text(s,encoding='utf-8')
print('Audio 2.2 applied')