from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
p=ROOT/'app/src/main/assets/index.html'
s=p.read_text(encoding='utf-8')

if 'living-dex-home-reference" content="5.1"' not in s:
    s=s.replace('</head>','<meta name="living-dex-home-reference" content="5.1"/>\n</head>',1)

css=r'''
/* Home Reference 5.1 — faithful approved Inicio with active-game artwork. */
#home .home-current-head{display:none!important}
#home .home-current-shell{max-width:780px!important;margin:0 auto!important;padding:0 0 24px!important}
#home .playing-card{min-height:0!important;padding:0!important;border-radius:30px!important;overflow:hidden!important;border:1px solid rgba(255,255,255,.6)!important;background:#142338!important;box-shadow:0 20px 48px rgba(35,48,79,.16)!important;color:#fff!important}
.home51-hero{position:relative;min-height:520px;padding:26px 28px 26px;display:flex;flex-direction:column;justify-content:flex-end;overflow:hidden}
.home51-bg{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;filter:saturate(.95) brightness(.82);transform:scale(1.02)}
.home51-shade{position:absolute;inset:0;background:linear-gradient(180deg,rgba(16,33,52,.06) 0%,rgba(16,31,49,.16) 34%,rgba(12,26,45,.88) 100%)}
.home51-top{position:absolute;top:24px;left:26px;right:26px;z-index:3;display:flex;align-items:center;justify-content:space-between;gap:12px}.home51-badge{display:inline-flex;align-items:center;gap:8px;background:#ff5555;color:#fff;border-radius:999px;padding:10px 15px;font-size:12px;font-weight:900;box-shadow:0 8px 22px rgba(255,85,85,.25)}.home51-badge i{width:8px;height:8px;border-radius:50%;background:#fff}.home51-platform{padding:9px 14px;border:1px solid rgba(255,255,255,.34);border-radius:999px;background:rgba(255,255,255,.10);backdrop-filter:blur(9px);font-size:11px;font-weight:850;color:#fff}
.home51-content{position:relative;z-index:3}.home51-cover{width:126px;height:168px;border-radius:18px;overflow:hidden;border:2px solid rgba(255,255,255,.75);box-shadow:0 14px 32px rgba(0,0,0,.24);margin-bottom:18px;background:#18263a}.home51-cover img{width:100%;height:100%;object-fit:cover;display:block}.home51-version{font-size:15px;font-weight:800;margin-bottom:5px;color:#fff}.home51-title{font-size:clamp(36px,8vw,52px);font-weight:950;letter-spacing:-.05em;line-height:.98;margin:0 0 22px;color:#fff;text-shadow:0 2px 12px rgba(0,0,0,.18)}.home51-progressline{display:grid;grid-template-columns:1fr auto;gap:18px;align-items:end}.home51-count{font-size:17px;font-weight:850}.home51-percent{font-size:34px;font-weight:950;line-height:1}.home51-bar{grid-column:1/-1;height:9px;border-radius:999px;background:rgba(255,255,255,.35);overflow:hidden}.home51-bar i{display:block;height:100%;border-radius:inherit;background:#ff5555}.home51-cta{width:100%;margin-top:24px;min-height:64px;border:0;border-radius:20px;background:linear-gradient(135deg,#ff5555,#ff615e);color:#fff;font-size:18px;font-weight:900;box-shadow:0 12px 26px rgba(255,85,85,.30)}
.home51-journey{margin-top:24px}.home51-jhead{display:flex;align-items:center;justify-content:space-between;gap:12px;margin:0 4px 14px}.home51-jtitle{display:flex;align-items:center;gap:12px;font-size:25px;font-weight:950;letter-spacing:-.04em;color:#17213c}.home51-jicon{width:42px;height:42px;border-radius:14px;background:#fff0f0;color:#ff5555;display:grid;place-items:center;font-size:21px}.home51-maplink{border:0;background:transparent;color:#17213c;font-size:14px;font-weight:850;display:flex;align-items:center;gap:5px}.home51-next{position:relative;padding:26px 26px 20px 92px;border-radius:28px;background:#fff;border:1px solid #edf0f5;box-shadow:0 8px 26px rgba(35,48,79,.08);min-height:130px}.home51-nexticon{position:absolute;left:24px;top:24px;width:54px;height:54px;border-radius:17px;background:#fff0f0;color:#ff5555;display:grid;place-items:center;font-size:24px}.home51-nextlabel{font-size:11px;font-weight:900;letter-spacing:.12em;color:#9aa4b7;text-transform:uppercase}.home51-nexttitle{font-size:21px;font-weight:950;letter-spacing:-.035em;color:#17213c;margin-top:8px}.home51-nextsub{font-size:12px;font-weight:650;color:#8e98aa;margin-top:8px}.home51-nextbar{height:7px;border-radius:999px;background:#edf0f5;margin-top:18px;overflow:hidden}.home51-nextbar i{display:block;height:100%;background:#ff5555;border-radius:inherit}.home51-chev{position:absolute;right:23px;top:34px;color:#c6ccd7;font-size:24px;font-weight:900}
#home .home232-journey,#home .home-journey-summary{display:none!important}
@media(max-width:680px){#home .home-current-shell{padding:0 2px 18px!important}.home51-hero{min-height:500px;padding:22px 20px}.home51-top{top:20px;left:20px;right:20px}.home51-cover{width:108px;height:145px}.home51-title{font-size:38px}.home51-next{padding:22px 20px 18px 82px}.home51-nexticon{left:18px;top:20px;width:50px;height:50px}.home51-jtitle{font-size:23px}.home51-platform{font-size:10px;padding:8px 11px}}
'''
if '/* Home Reference 5.1' not in s:
    s=s.replace('</style>',css+'\n</style>',1)

js=r'''
// Home Reference 5.1
function home51Art(g){const key=((g&&g.id)||'').toLowerCase(),name=((g&&g.name)||'').toLowerCase();if(key.includes('lets')||name.includes("let's go"))return 'assets/ui45/letsgo.jpg';if(key.includes('sword')||key.includes('shield')||name.includes('sword')||name.includes('shield'))return 'assets/ui45/swsh.jpg';if(key.includes('bd')||key.includes('sp')||name.includes('diamond')||name.includes('pearl'))return 'assets/ui45/bdsp.jpg';if(key.includes('arceus')||name.includes('arceus'))return 'assets/ui45/arceus.jpg';if(key.includes('sv')||name.includes('scarlet')||name.includes('violet'))return 'assets/ui45/sv.jpg';if(key.includes('za')||name.includes('z-a'))return 'assets/ui45/za.jpg';return 'assets/ui45/sv.jpg'}
function home51Next(g,p){const sv=((g.id||'').toLowerCase().includes('sv')||(g.name||'').toLowerCase().includes('scarlet')||(g.name||'').toLowerCase().includes('violet'));if(sv&&window.SV_ROUTE){let done=[];try{done=typeof ref43DoneArray==='function'?ref43DoneArray():[]}catch(e){};let n=1;while(n<=18&&done.includes(n))n++;if(n<=18&&SV_ROUTE[n-1]){const r=SV_ROUTE[n-1];const level=Array.isArray(window.REF49_LEVELS)?REF49_LEVELS[n-1]:'';return {title:r[0],sub:`Siga a progressão recomendada${level?' · Lv.'+level:''}`,pct:Math.round((done.length/19)*100)}}}return {title:'Continue sua jornada',sub:`Avance na Pokédex de ${g.name}`,pct:p.pct||0}}
function renderActiveGameHome(){const home=document.getElementById('home');if(!home)return;let shell=home.querySelector('.home-current-shell');if(!shell){shell=document.createElement('div');shell.className='home-current-shell';home.prepend(shell)}const g=GAMES.find(x=>x.id===state.activeGameId);if(!g){shell.innerHTML=`<div class="empty-current"><div class="icon">◉</div><h2>Nenhum jogo atual</h2><p>Escolha um jogo na Biblioteca para ele ocupar a tela inicial.</p><button class="btn primary" onclick="go('games')">Escolher jogo atual</button></div>`;return}const p=activeGameProgress(g),art=home51Art(g),version=selectedVersion(g.id)||g.name,next=home51Next(g,p);shell.innerHTML=`<div class="playing-card"><div class="home51-hero"><img class="home51-bg" src="${art}" alt="" draggable="false"><div class="home51-shade"></div><div class="home51-top"><span class="home51-badge"><i></i> Jogo atual</span><span class="home51-platform">${g.platform||'Nintendo Switch'}</span></div><div class="home51-content"><div class="home51-cover"><img src="${art}" alt="Capa de ${g.name}"></div><div class="home51-version">${version}</div><h2 class="home51-title">${g.name}</h2><div class="home51-progressline"><div class="home51-count">${p.caught} / ${p.total||g.count||0} Pokémon</div><div class="home51-percent">${p.pct}%</div><div class="home51-bar"><i style="width:${p.pct}%"></i></div></div><button class="home51-cta" onclick="continueActiveGame()">Continuar jornada</button></div></div></div><section class="home51-journey"><div class="home51-jhead"><div class="home51-jtitle"><span class="home51-jicon">⌂</span>Jornada</div><button class="home51-maplink" onclick="typeof ref42Open==='function'?ref42Open('map'):continueActiveGame()">Ver mapa ›</button></div><button class="home51-next" onclick="continueActiveGame()" style="width:100%;text-align:left;border:0"><span class="home51-nexticon">⌁</span><span class="home51-nextlabel">Próximo objetivo</span><span class="home51-nexttitle">${next.title}</span><span class="home51-nextsub">${next.sub}</span><span class="home51-nextbar"><i style="width:${next.pct}%"></i></span><span class="home51-chev">›</span></button></section>`}
window.renderActiveGameHome=renderActiveGameHome;
setTimeout(()=>{try{renderActiveGameHome()}catch(e){}},0);
'''
if '// Home Reference 5.1' not in s:
    s=s.replace('</body>','<script>'+js+'</script>\n</body>',1)

p.write_text(s,encoding='utf-8')
print('Home Reference 5.1 applied')
